[WIP] Fix draw within screen
Rinkeeee96/FoxTrot_SA_Engine pull request #107
Opened 2020-11-24 12:35 UTC by TheLarsJansen

2020-11-24 15:30 UTC, ttleeuw commented on Glitch/Assets/Levels/Maps/Level1.json
> +         "properties":[
grond altijd tekenen ondanks dat het niet in het scherm is?

2020-11-25 09:44 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	return false;;
;

2020-11-25 11:03 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	vector<Drawable*> API getAllAlwaysDrawablesInScene();
Als je deze niet meer gebruikt weghalen

2020-11-26 09:59 UTC, wieltar commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +bool VideoEngine::checkInScreen(Object* obj) {
Misschien deze even duidelijker benoemen, je kijkt of je objecten moet tekenen

2020-11-26 10:14 UTC, wieltar commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +bool VideoEngine::checkInScreen(Object* obj) {
en let op const ref als je niets aanpast

2020-11-26 10:14 UTC, wieltar commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +bool VideoEngine::checkInScreen(Object* obj) {
en de objLeft etc. dat zijn de hoeken of de zijden?

2020-11-26 10:15 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +const void Scene::addNewObjectToLayer(const int zIndex, Object* object, bool renderPhysics, bool alwaysDraw)
pas de benaming aan van alwaysDraw zodat het duidelijk is dat het gaat over een layer

2020-11-26 11:57 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	if ((objRight	> videoFacade->getXCameraOffset() && objRight	< videoFacade->getXCameraOffset() + WINDOW_WIDTH &&
Voor leesbaarheid zou ik de camera offset bij het object optellen en niet andersom

2020-11-26 12:07 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	if ((objRight	> videoFacade->getXCameraOffset() && objRight	< videoFacade->getXCameraOffset() + WINDOW_WIDTH &&
Hou zou ik kunnen kijken of de rechterkant van een object groter is dan de camera offset als ik ze bij elkaar optel?
Of begrijp ik je nu verkeerd?

2020-11-26 12:07 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	if ((objRight	> videoFacade->getXCameraOffset() && objRight	< videoFacade->getXCameraOffset() + WINDOW_WIDTH &&
Ik tel sws niks bij elkaar op, alleen de scherm breedte bij de offset want dan krijg je de rechter kant van het scherm

2020-11-26 12:09 UTC, ttleeuw commented on Glitch/Game/Levels/Builders/LevelBuilder.cpp
> +					part->setWidth(width);
this->setWidth(objectValue["width"]) zelfde bij height

2020-11-26 12:09 UTC, ttleeuw commented on Glitch/Game/Scenes/WinScreen/WinScreen.cpp
> +	addNewObjectToLayer(0, layer0, false, true);
Default values gebruiken? Komt best veel terug en is van toepassing op iedere knop, background etc die we aanmaken.

2020-11-26 12:09 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	if ((objRight	> videoFacade->getXCameraOffset() && objRight	< videoFacade->getXCameraOffset() + WINDOW_WIDTH &&
comments erboven zodat duidelijk is welke hoek wordt gecheckt

2020-11-26 12:09 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +					Drawable* drawable = dynamic_cast<Drawable*>(obj.second);
getAllDrawables in scene nog wel nodig, of wordt deze helemaal niet meer gebruikt

2020-11-26 12:09 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +					Drawable* drawable = dynamic_cast<Drawable*>(obj.second);
Voor de zekerheid if check eromheen;
if(Drawable* drawable = dynamic_cast<Drawable*>(obj.second))

2020-11-26 12:41 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +					Drawable* drawable = dynamic_cast<Drawable*>(obj.second);
Ik heb een regel lager de if staan of die het goed gedaan heeft
Doet inprincipe toch hetzelfde?
Maar zal hem even aanpassen
![image](https://user-images.githubusercontent.com/43005884/100352206-effc2a80-2fec-11eb-98f9-a89ba0cc82ba.png)

2020-11-26 12:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +					Drawable* drawable = dynamic_cast<Drawable*>(obj.second);
Wordt nog gebruikt door andere dingen

2020-11-26 12:44 UTC, TheLarsJansen commented on Glitch/Game/Scenes/WinScreen/WinScreen.cpp
> +	addNewObjectToLayer(0, layer0, false, true);
Ik heb een create layer gemaakt. Wil je dat ik die aanroep voor de knoppen en dan die values daarin zet?
Want de default values zijn false, false en die aanpassen is niet echt een optie

2020-11-26 15:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +					Drawable* drawable = dynamic_cast<Drawable*>(obj.second);
Klopt maar scheelt een regel code en leest iets makkelijker

2020-11-26 16:08 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	if ((objRight	> videoFacade->getXCameraOffset() && objRight	< videoFacade->getXCameraOffset() + WINDOW_WIDTH &&
Ja dat zou ik dus omdraaien. 
Kwa werking verandert er niks. Maar leesbaarheid wel.
Je kan het ook zo laten staan.

2020-11-26 16:08 UTC, Rinkeeee96 approved these changes

2020-11-27 06:36 UTC, ttleeuw reviewed
Ik ben de achtergrond kwijt, code niks meer op aan te merken

2020-11-27 08:52 UTC, WilliamRossAvans requested changes

2020-11-27 08:52 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/ParticleAdapter.h
> +	void setWidth(float width) { this->width = width; }
API

2020-11-27 12:37 UTC, Rinkeeee96 approved these changes

2020-11-27 14:53 UTC, ttleeuw approved these changes

2020-11-27 14:58 UTC, WilliamRossAvans approved these changes

2020-11-27 14:58 UTC, merged