Feature/hud
Rinkeeee96/FoxTrot_SA_Engine pull request #109
Opened 2020-11-26 07:58 UTC by ttleeuw

2020-11-26 09:41 UTC, ttleeuw commented on Glitch/Game/Levels/Level.cpp
> +	for (size_t i = 0; i < (player->getTotalHealth() - player->getHealth()); i++)
Total + current

2020-11-26 09:47 UTC, ttleeuw commented on Glitch/Game/Characters/Player/Player.cpp
> +	this->setTotalHealth(3);
Set total healt, if set health > totalHealth, totalHealth = health

2020-11-26 09:48 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +		(*pointerToCurrentScene)->setXCameraOffset(videoFacade->getXCameraOffset());
Check if;
Handle update in scene;
handle hud in layer (static)

2020-11-26 09:49 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::updateHudPositions() {
make private

2020-11-26 09:50 UTC, wieltar requested changes

2020-11-26 09:50 UTC, wieltar commented on Glitch/Game/Levels/Level.cpp
> +		health1->setPositionY(100);
dit is dubbel  met regel 64

2020-11-26 09:50 UTC, wieltar commented on Glitch/Game/Levels/Level.cpp
> +		health1->setPositionY(100);
Ik zou alleen de aanpassingen doen in de loops

2020-11-26 09:50 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	for (size_t i = 0; i < huds.size(); i++)
misschien veranderen naar hudElements of hudElemenContainer? en protected maken voor scene

2020-11-26 09:50 UTC, wieltar commented on Glitch/Game/Levels/Level.cpp
> +		auto* health1 = new Drawable(startingID--);
deze wordt ook nooit verwijderd en het zijn geen smart ptrs

2020-11-26 09:50 UTC, ttleeuw commented on Glitch/Game/Levels/Level.cpp
> +	player->setHealth(2);
if health > total, total = health

2020-11-26 09:53 UTC, TheLarsJansen requested changes

2020-11-26 09:53 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.cpp
> +}
Je maakt 2 healt pointers aan maar die verwijder je nergens. Miss kan je proberen er geen pointers van te maken dan hoeft er ook niks verwijderd te worden. Of 1x bij een setup de pointers aanmaken en en dan bij het einde van het level te verwijderen. En SMART POINTERS natuurlijk :)

2020-11-26 09:53 UTC, TheLarsJansen commented on Glitch/Game/Characters/ICharacter.h
> +	void setTotalHealth(int val) { this->totalHealth = val; }
Hier een if statement inmaken waar je kijkt of val hoger is dan totalHealth, dan kan je nooit meer levens krijgen dan je max kan hebben

2020-11-26 09:53 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.cpp
> +	int startingID = -662;
Is er geen "slimme" manier om ID's te krijgen?

2020-11-26 11:53 UTC, Rinkeeee96 commented on Glitch/Game/Levels/Level.cpp
> +	int startingID = -662;
@TheLarsJansen Static class maken die je overal kan aanroepen om free ids te krijgen een optie? #letsaddstaticclasses

2020-11-26 11:58 UTC, ttleeuw commented on Glitch/Game/Levels/Level.cpp
> +}
Delete in Scene; onDetach

2020-11-26 12:04 UTC, TheLarsJansen reviewed
Ff die warning fixen en dan is die wat mij betreft goed!

2020-11-26 12:04 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.cpp
> +	health1->setPositionX((startingXAxis + (xAxisChange * (current + 1))));
Geeft conversion warning 😕

2020-11-26 12:34 UTC, TheLarsJansen approved these changes

2020-11-26 14:11 UTC, TheLarsJansen submitted a review, later dismissed

2020-11-26 14:53 UTC, TheLarsJansen approved these changes

2020-11-27 08:58 UTC, WilliamRossAvans commented on Glitch/Game/Levels/Level.cpp
> +void Level::addHuds() {
Doxygen

2020-11-27 08:58 UTC, WilliamRossAvans commented on Glitch/Game/Levels/Level.cpp
> +void Level::addHealthHud(int& startingID, int& startingXAxis, int& xAxisChange, int& current, SpriteObject* HUD) {
Doxygen

2020-11-27 10:26 UTC, TheLarsJansen submitted a review, later dismissed

2020-11-30 13:56 UTC, wieltar commented on Glitch/Game/Levels/Level.cpp
> +	this->huds = std::vector<Drawable*>();
Kan dit niet in addHuds()?

2020-11-30 14:02 UTC, Rinkeeee96 approved these changes
Ziet er netjes uit. Nieuwe PR dus met een levens buffer inbouwen?

2020-11-30 15:47 UTC, wieltar approved these changes

2020-12-02 10:14 UTC, wieltar approved these changes

2020-12-02 12:05 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Slime.h
> +					this->player->setCurrentHealth(this->player->getCurrentHealth() - 1);
Misschien gwn een -- operator maken?

2020-12-02 12:05 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Slime.h
> +					this->player->setCurrentHealth(this->player->getCurrentHealth() - 1);
this->player->health()--;

2020-12-02 12:05 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Slime.h
> +					this->player->setCurrentHealth(this->player->getCurrentHealth() - 1);
Iets kwa netheid

2020-12-02 12:07 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Player/Player.cpp
> +	this->setCurrentHealth(3);
Je kan dit ook gwn bij de variabele zetten, hoef je niet los die functie aan te roepen

2020-12-02 13:26 UTC, TheLarsJansen approved these changes

2020-12-02 13:40 UTC, Rinkeeee96 approved these changes

2020-12-02 13:40 UTC, merged