Fix/btn
Rinkeeee96/FoxTrot_SA_Engine pull request #110
Opened 2020-11-26 08:59 UTC by WilliamRossAvans

change the constructor of the btn

2020-11-26 09:35 UTC, wieltar approved these changes

2020-11-26 10:00 UTC, TheLarsJansen requested changes

2020-11-26 10:00 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Overworld/Overworld.cpp
> +	level1Btn = new Button(1, ColoredText("", Color(255, 255, 255)), BIND_FN(onLevel1BtnClick), new SpriteObject(101012, 11, 15, 1, 300, "Assets/Buttons/village_yellow.png"));
Het is nu niet echt duidelijk wat een level is in overworld. Ik was maar gewoon aan het spammen met klikken en toen zat ik er ineens in

2020-11-27 07:04 UTC, ttleeuw commented on Glitch/Game/Scenes/DeathScreen/DeadScreen.cpp
> +	auto btnSprite = new SpriteObject(-601, 40, 116, 1, 300, "Assets/Buttons/btn_gray_round.png");
Worden deze in btn, drawable of in scene beheerd?

2020-11-27 07:04 UTC, ttleeuw commented on Glitch/Game/Scenes/DeathScreen/DeadScreen.cpp
> +	startBtn = new Button(-600, ColoredText("Restart", Color(0, 0, 0)), BIND_FN(onReStartBtnClick), btnSprite);
Wordt opgeslagen maar nergens opgeruimd

2020-11-27 07:05 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Objects/Button.cpp
> +		if (isMouseOver && hasHoverSprite) {
hasHoverSprite heel specifiek, hooverable of iets dergelijks?

2020-11-27 07:06 UTC, ttleeuw reviewed
Ziet er netjes uit, functioneel zou ik de knoppen wel iets meer laten opvallen in de overworld. Niet echt opvallend waar nu levels zitten

2020-11-27 08:53 UTC, WilliamRossAvans commented on Glitch/Game/Scenes/DeathScreen/DeadScreen.cpp
> +	auto btnSprite = new SpriteObject(-601, 40, 116, 1, 300, "Assets/Buttons/btn_gray_round.png");
drawable

2020-11-27 08:54 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/SceneManager/Objects/Button.cpp
> +		if (isMouseOver && hasHoverSprite) {
In princiepe is elke btn hoverable, en om een hover te laten zien moet je een hover sprite hebben, en dit wordt ook pas geregeld als er een hover sprite is, vandaar deze naamkeuze

2020-11-27 09:30 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Objects/Button.cpp
> +		int hoverSpriteId = DEFAULT_SPRITEID;
dit assignment lijkt me onnodig, het kan werken met de defines als je de ; erachter weghaald, scheelt weer verwarring in het assiginen van een hover sprite id terwijl je er niet overheen gaat

2020-11-27 09:36 UTC, wieltar requested changes

2020-11-27 09:36 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Objects/Button.cpp
> +	int hoverSpriteId = HOVER_SPRITEID;
waarom wordt hier het spriteId niet opgeslagen en gebruikt?

2020-11-27 10:45 UTC, TheLarsJansen approved these changes
Ziet er volgens mij prima uit!

2020-11-27 10:58 UTC, wieltar approved these changes

2020-11-27 11:03 UTC, Rinkeeee96 approved these changes

2020-11-27 11:03 UTC, merged