[WIP] Feature/credits
Rinkeeee96/FoxTrot_SA_Engine pull request #111
Opened 2020-11-26 10:34 UTC by ttleeuw

2020-12-02 13:33 UTC, Rinkeeee96 approved these changes
Beetje jammer dat ik onderaan sta. 5Euro kom ik dan bovenaan?

2020-12-02 13:34 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/MainMenu/MainMenu.cpp
> +	//addNewObjectToLayer(3, loadBtn);
Verwijderen of?

2020-12-02 13:36 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +	//if (sprite == NULL) {
weg?

2020-12-02 13:38 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +		drawMessageAt(*object.toString(), Position(destination.x, destination.y), ObjectSize(MESSAGE_WIDTH, MESSAGE_HEIGHT));
Nu pak je hier een set breedte en lengte? Klopt dit wel? Wil je dit niet dynamisch hebben

2020-12-02 13:39 UTC, TheLarsJansen commented
![image](https://user-images.githubusercontent.com/43005884/100879812-313c8080-34ac-11eb-8fa4-0a2a17f159d5.png)

De fade out is net te laat

2020-12-02 13:46 UTC, TheLarsJansen requested changes

2020-12-02 13:46 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Credits/CreditsScene.cpp
> +	backBtn->setPositionY(WINDOW_HEIGHT - 10 - backBtn->getHeight());
Waarom wordt de knop 2x aangemaakt?

2020-12-02 13:46 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Credits/CreditsScene.cpp
> +	backBtn->setPositionY(WINDOW_HEIGHT - 10 - backBtn->getHeight());
Hij staat trouwens denk ik ook op een verkeerde layer want hijs niet te zien

2020-12-02 13:46 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +		videoFacade->drawMessageAt(m, p, ObjectSize(100, 50));
Magic numbers

2020-12-02 14:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +		drawMessageAt(*object.toString(), Position(destination.x, destination.y), ObjectSize(MESSAGE_WIDTH, MESSAGE_HEIGHT));
![image](https://user-images.githubusercontent.com/31704739/100882955-0ce2a300-34b0-11eb-83f6-5b467c71b28e.png)
Het kan, het nadeel daarvan is dat geen enkele button hiervan is uitgegaan en dat de verhoudingen niet meer kloppen qua text (zie afbeelding hierboven)

2020-12-02 14:09 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +		drawMessageAt(*object.toString(), Position(destination.x, destination.y), ObjectSize(MESSAGE_WIDTH, MESSAGE_HEIGHT));
Ahhhhh oke, dan nvm.

2020-12-02 14:11 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Credits/CreditsScene.cpp
> +	auto* name4 = new Text(7, new ColoredText("Rinke de Vries", Color(0, 0, 0)), SHORT_NAME_WIDTH, TEXT_HEIGHT, CENTER_X + RIGHT_X_CENTER, CENTER_Y - 150);
:kissing_heart:

2020-12-02 14:55 UTC, TheLarsJansen approved these changes

2020-12-03 12:39 UTC, Rinkeeee96 approved these changes

2020-12-03 13:37 UTC, wieltar approved these changes

2020-12-03 13:37 UTC, merged