[W.I.P] Feature/level2level3
Rinkeeee96/FoxTrot_SA_Engine pull request #113
Opened 2020-11-26 14:03 UTC by Maxvani

2020-11-26 15:19 UTC, Rinkeeee96 commented
Misschien eerste statemachine doorvoeren voordat deze erin gaat

2020-11-26 15:24 UTC, Maxvani commented
> Misschien eerste statemachine doorvoeren voordat deze erin gaat
👌

2020-11-26 16:40 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Fleye.h
> +		if (std::find(collidedDirection.begin(), collidedDirection.end(), Direction::UP) != collidedDirection.end()) {
Misschien hiermee iets in de base classen doen, Slime, Fleye en dumpkin doen hetzelfde

2020-11-26 16:40 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +		auto collisionEvent = static_cast<OnCollisionBeginEvent&>(event);
Zie comment Flye

2020-11-26 16:41 UTC, ttleeuw commented on Glitch/Game/Game.cpp
> +	LoadLevelFacade level2Loader{ engine };
Even kijken hoe dit samen gaat vallen met Scene switchen van rinke

2020-11-26 16:42 UTC, ttleeuw commented on Glitch/Game/Levels/Builders/LevelBuilder.cpp
> +	auto fleyeDefault = new SpriteObject(textureId++, 42, 42, 1, 200, "Assets/Sprites/Enemies/Fleye.png");
Hebben we aniematies?

2020-11-26 16:44 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsFacade.cpp
> +	vel.y = body->GetLinearVelocity().y;
Deze zijn weggehaald, niet meer nodig. Object houdt binnen box2d velocity die niet geset wordt

2020-11-26 17:55 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Physics/PhysicsFacade.cpp
> +	vel.y = body->GetLinearVelocity().y;
Ik heb hier wel een idee over, morgen even over hebbem

2020-11-26 17:55 UTC, WilliamRossAvans commented on Glitch/Game/Game.cpp
> +	LoadLevelFacade level2Loader{ engine };
Ik heb hier wel een idee voor, morgen even over hebbem

2020-11-27 09:35 UTC, TheLarsJansen commented
Heb nog niet naar de code gekeken en alleen gespeeld.
Dingen die me opvallen
- De levels zijn erg kaal, geen decoraties, geen wolken, beetje "saai".
- In level 3 kan je links bovenin niet verder, de sprite kan niet door het gat heen.
- De jumpkin zou achter je aan moeten komen maar dat doet ie niet.
- Links van de levels zou een win trigger zitten als "cheat", heb ik niet gevonden.
- De 2e jumpkin in level 3 is moeilijk te killen. Volgens mij zit er nu ook een bug in dat je tegen de zijkant springt dat ze enemies dan ook dood gaan.
- De fleye is wel fancy!

2020-11-27 09:48 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +	void onUpdate() override {
Hier zit denk ik een klein foutje aangezien de jumpkin niet echt op je af komt

2020-11-27 09:52 UTC, Maxvani commented on Glitch/Game/Levels/Builders/LevelBuilder.cpp
> +	auto fleyeDefault = new SpriteObject(textureId++, 42, 42, 1, 200, "Assets/Sprites/Enemies/Fleye.png");
Ja er zijn animerende sprites voor de 2 nieuwe enemies alleen zag ik dat er een taak/US was voor dit dus komt in een latere PR

2020-11-27 10:46 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/Fleye.h
> +		if (std::find(collidedDirection.begin(), collidedDirection.end(), Direction::UP) != collidedDirection.end()) {
Dit fix ik wel in de animaties PR zodat deze PR er doorheen kan

2020-11-30 10:50 UTC, wieltar requested changes
Level 2 is compleet broken, de knop main menu in overworld sluit het spel af

2020-11-30 11:25 UTC, Rinkeeee96 requested changes
Level 2 is kapot. Level 2-3 restart gaat naar level 1. Knoppen zijn niet goed

2020-11-30 11:26 UTC, Rinkeeee96 submitted a review, later dismissed
Beide level 2 en 3 zouden particles krijgen. Regen moet er nog bij.

2020-11-30 12:57 UTC, Maxvani commented
> Beide level 2 en 3 zouden particles krijgen. Regen moet er nog bij.

Regen zit in level 2, alleen toen scalede de particles nog niet mee, dacht dat dit gefixt zou zijn met een andere PR

2020-11-30 16:10 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/DeathScreen/DeathScreen.cpp
> +	stateMachine->switchToScene(stateMachine->getCurrentSceneIdentifier(), true);
Dit was precies wat ik bedoelde, lag dus niet aan de positie van de buttons

2020-11-30 16:48 UTC, TheLarsJansen commented
Level 3 ziet er zo uit dus is volgens mij niet de bedoeling...
![image](https://user-images.githubusercontent.com/43005884/100637734-7e491700-3333-11eb-956c-47ab8cee67fb.png)

Level 2 restart button wijst naar overworld

2020-11-30 17:05 UTC, TheLarsJansen requested changes

2020-11-30 17:05 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Overworld/Overworld.cpp
> +	level3Btn->setPositionY(850);
Mijn vriendin vindt dat Level 1 en Level 3 van positie moet wisselen, en haar wil is wet 😝

2020-11-30 17:05 UTC, TheLarsJansen commented on Glitch/Game/Scenes/DeathScreen/DeathScreen.cpp
> +	stateMachine->switchToScene(stateMachine->getCurrentSceneIdentifier(), true);
Ik zie dat er ook een getCurrentLevelIdentifier bestaat. Misschien die proberen, want level2 restart wijst naar overworld dus dat klopt niet

2020-11-30 19:40 UTC, Maxvani commented on Glitch/Game/Scenes/DeathScreen/DeathScreen.cpp
> +	stateMachine->switchToScene(stateMachine->getCurrentSceneIdentifier(), true);
Lag wel aan de posities, deze wordt alleen gezet bij het switchen naar een level

2020-11-30 19:49 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/DeathScreen/DeathScreen.cpp
> +	stateMachine->switchToScene(stateMachine->getCurrentSceneIdentifier(), true);
Dit fixt wel wat ik bedoelde.. Dus lag niet aan het verwijderen van de knoppen.

2020-12-01 06:37 UTC, ttleeuw commented
Levels zijn mooi en de enemies zijn goed, als dit op development komt issue van maken mbt het doodgaan van enemies tegen de muur.

Kleine dingen;
- Particles, er is nergens iets van een particle (regen)
- Verschillende levels spelen, de textures worden fout ingeladen als er van level geswitchted wordt ik vind dat dit bij dit PR zou moeten horen (wordt hier gebruik van gemaakt)

2020-12-02 13:20 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Fleye.h
> +					this->player->kill();
Volgensmij gebruiken we geen kill functie meer?

2020-12-02 13:20 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Fleye.h
> +					this->player->kill();
Oh wacht nvm dat is in de Huds pr van @ttleeuw

2020-12-02 13:21 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +			EventSingleton::get_instance().dispatchEvent<ActionEvent>((Event&)ActionEvent(Direction::UP, this->getObjectId()));
We hebben geen event singleton meer? Dus dit graag aanpassen naar de nieuwe.

2020-12-02 13:25 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +			EventSingleton::get_instance().dispatchEvent<ActionEvent>((Event&)ActionEvent(Direction::UP, this->getObjectId()));
Even develop mergen

2020-12-02 13:26 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +		LevelBuilder levelOneBuilder{ engine, sceneId++, levelToBuild * 999 };
Waarom die 999? Magic number definition. Is dit gwn om een bug te omzijlen?

2020-12-02 13:27 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +		levelOneBuilder.cleanup();
Waar is die cleanup voor? 2 regels hieronder raak de levelbuilder buiten zn scope en wordt hij toch al opgeruimd. Dan is zelf opruimen niet meer nodig? Of zet het in de destructor

2020-12-02 13:27 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/General/Debug.h
> +#define DEBUG_MAIN true
Niet naar develop

2020-12-02 13:28 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsBody.h
> +	float gravity = 1;
Magic number?

2020-12-02 13:29 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Objects/Object.h
> +	float gravity = 1;
Wat is die 1?

2020-12-02 13:36 UTC, Maxvani commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +		LevelBuilder levelOneBuilder{ engine, sceneId++, levelToBuild * 999 };
Dit is zodat de textureId's niet aan elkaar gelijk kunnen zijn in de builder voor nieuwe levels, zal hem wel ffe Definen

2020-12-02 14:13 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +		LevelBuilder levelOneBuilder{ engine, sceneId++, levelToBuild * 999 };
Idk of je dat echt wil doen. Zou even kijken waarom ze gelijk zijn? Als het goed is worden alle textures verwijdert na elke screen change. Dus dan zouden de IDS weer vrij moeten zijn

2020-12-02 14:50 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Fleye.h
> +					this->player->kill();
Even kijken hoe Thijs dit doet, kill is deprecated

2020-12-02 14:50 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +					this->player->kill();
Zelfde hier

2020-12-02 14:52 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +		LevelBuilder levelOneBuilder{ engine, sceneId++, *this, levelToBuild * TextureIDOffset };
Kun je die 999 anders doen?

2020-12-02 15:22 UTC, TheLarsJansen reviewed
Als de dingen die Rinke aangegeven heeft verwerkt zijn vind ik hem mooi

2020-12-02 15:25 UTC, TheLarsJansen commented
Heb de regen particle tikkie groter gemaakt dus nu is die iets beter te zien

2020-12-02 16:42 UTC, Rinkeeee96 commented on Glitch/Game/Levels/Builders/ILevelBuilder.h
> +	virtual int GetLastTextureId() = 0;
Hier staat nog een leftover

2020-12-02 16:44 UTC, Rinkeeee96 commented on Glitch/Game/Levels/Builders/LevelBuilder.h
> +	int GetLastTextureId() override;
Leftover

2020-12-02 16:51 UTC, Rinkeeee96 approved these changes

2020-12-02 20:27 UTC, TheLarsJansen commented
Heb de positie van de knoppen nog even veranderd, vind het zo logischer. Had ik al eerder gecomment maar weet niet of dat nou ook al aangepast was, volgens mij wel maar geen idee dus heb het even gedaan.

2020-12-02 20:34 UTC, TheLarsJansen requested changes
Schiet me ineens te binnen dat level 3 nog niet goed meebeweegt boven in

2020-12-03 06:37 UTC, ttleeuw commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +		LevelBuilder levelOneBuilder{ engine, sceneId++, *this };
Private variable van SceneStateMachine?

2020-12-03 06:37 UTC, ttleeuw commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
>  		LoadLevelFacade levelLoader{ engine };
Private variable van SceneStateMachine?

2020-12-03 06:38 UTC, ttleeuw commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +		LevelBuilder levelOneBuilder{ engine, sceneId++, *this };
Wordt vaker gebruikt, het enige wat veranderd is param voor .load

2020-12-03 06:45 UTC, ttleeuw submitted a review, later dismissed

2020-12-03 06:46 UTC, ttleeuw commented
Ziet er goed uit, dingetje van camera van lars fixen en ik keur hem goed

2020-12-03 12:44 UTC, Rinkeeee96 requested changes
De berekening van de camera offset is geen fix op het probleem, alleen omzijlen

2020-12-04 08:47 UTC, ttleeuw approved these changes

2020-12-04 08:59 UTC, Rinkeeee96 approved these changes

2020-12-04 09:20 UTC, TheLarsJansen approved these changes

2020-12-04 09:20 UTC, merged