Keymapping
Rinkeeee96/FoxTrot_SA_Engine pull request #119
Opened 2020-11-28 14:03 UTC by wieltar

2020-12-01 06:43 UTC, ttleeuw commented on Glitch/Game/Characters/Player/Player.cpp
> +				StopMovementCommand command(*this);
Kan dit niet al in de invoker?

2020-12-01 06:44 UTC, ttleeuw commented on Glitch/Game/Levels/Level.cpp
> +commandBuilder{ new CommandBuilder() }
Geen pointer, maar gewoon class? anders unique pointer?

2020-12-01 06:46 UTC, ttleeuw commented on engineFoxtrot/Engine/Events/InputMapping/CaptureInputEvent.h
> +	const MouseCode* pressedMouseButton
Reference?

2020-12-01 06:46 UTC, ttleeuw commented on engineFoxtrot/Engine/Events/InputMapping/CaptureInputEvent.h
> +	CaptureInputEvent(const MouseCode& _mouseCode) : pressedMouseButton{ &_mouseCode } {};
Single responsibility principle

2020-12-01 06:48 UTC, ttleeuw commented on engineFoxtrot/Engine/Events/InputMapping/ReleaseInputEvent.h
> +/// ReleaseInputEvent is fired when input capturing is done and events should be released again
Als ik zoek op; 
- ReleaseInput
- CaptureInput

Wordt het nergens gebruikt behalve in files;
-  engineFoxtrot/Engine/Events/EventType.h
- engineFoxtrot/Engine/Events/InputMapping/CaptureInputEvent.h 
- engineFoxtrot/Engine/Events/InputMapping/ReleaseInputEvent.h

2020-12-01 06:49 UTC, ttleeuw requested changes
Ziet over het algemeen goed uit, paar opmerkingen

2020-12-06 17:03 UTC, TheLarsJansen reviewed
Ziet er wel goed uit.
Vind wel dat het stoppen met lopen ook in deze PR hoort. Anders is het geen vooruitgang en gaan we er op develop op achteruit.
Ik kan aankomende week wel even meedenken.

2020-12-06 17:16 UTC, wieltar commented on Glitch/Game/Characters/Player/Player.cpp
> +	// hoe komen we hier aan pressed key?
was meer om te kijken naar het stop commando op deze plaats

2020-12-07 07:31 UTC, ttleeuw commented on Glitch/Commands/CommandBuilder.cpp
> +// TODO read keybinds from file
Niet op develop?

2020-12-07 07:32 UTC, ttleeuw commented on Glitch/Commands/CommandBuilder.cpp
> +#include "Commands/Character_commands/MoveRightcommand.h"
Zou CharacterCommands van maken

2020-12-07 07:32 UTC, ttleeuw commented on Glitch/Commands/Factory/CommandCreator.h
> +	//ICommand* create() { return new T(key); }
weg?

2020-12-07 07:32 UTC, ttleeuw commented on Glitch/Commands/Factory/CommandFactory.cpp
> +//ICommand* CommandFactory::create(const std::string& classname)
weg?

2020-12-07 07:33 UTC, ttleeuw commented on Glitch/Commands/Factory/CommandFactory.h
> +	//ICommand* create(const std::string& classname);
weg?

2020-12-07 07:35 UTC, ttleeuw commented on Glitch/Commands/exceptions/unknownCommandException.h
> +    //int error_number;               ///< Error number
weg?

2020-12-07 07:35 UTC, ttleeuw commented on Glitch/Commands/exceptions/unknownCommandException.h
> +class unknownCommandException : virtual public std::exception {
Nette manier van Exceptions, maar zou met consitency redenen andere gebruiken

2020-12-07 07:37 UTC, ttleeuw commented on Glitch/Game/Characters/Player/Player.cpp
> +		StopMovementCommand(*this, "stopMovement").execute(this->dispatcher);
Aparte Invoker of koppelen aan andere invoker, zorgt ervoor dat het makkelijker uit te breiden is. 
(Als dit het enige is wat naar key released moet luisteren misschien niet ivm Kiss)

2020-12-07 07:38 UTC, ttleeuw commented on Glitch/Game/Game.cpp
> +		engine.useCustomCommandInvoker(commandBuilder->readBindingsAndCreateInvoker());
Hoe wordt dit veranderd als men dit in game veranderd?

2020-12-07 07:39 UTC, ttleeuw commented on Glitch/Game/Game.h
> +	ICommandBuilder* commandBuilder;
pointer?

2020-12-07 07:40 UTC, ttleeuw commented on Glitch/Game/Levels/Level.cpp
> +		commandBuilder->buildPlayerCommands(*this->player, gameInvoker);
Kan dit in het Level niet meer veranderen? (Misschien met betrekking tot ontwikkel snelheid afspreken van niet, maar weet niet hoe de rest hier overdenkt. Zo even opgooien in de standup)

2020-12-07 07:41 UTC, ttleeuw commented on Glitch/Game/Levels/Level.h
> +	GameKeypressInvoker* gameInvoker;
Moet het level de commandbuilder en invoker kennen?

2020-12-07 08:14 UTC, ttleeuw commented
Pauze zit nu ook in develop, dit al meenemen?

2020-12-09 16:10 UTC, WilliamRossAvans requested changes

2020-12-10 10:54 UTC, TheLarsJansen reviewed
Heb er ff globaal overheen gekeken.
Ziet er wel prima uit.
Denk wel ff aan doxygen

2020-12-10 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +// TODO listen to pause event
TODO? Done?

2020-12-10 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +bool ParticleEngine::onPauseEvent(const Event& event)
Done I guess

2020-12-10 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Input/Commands/exceptions/unknownCommandException.h
> +class unknownCommandException : virtual public std::exception {
Ziet er heel fancy uit. Maaaaaaaaaaaaaaaaar,
Niet echt consistent met de rest van de exceptions

2020-12-10 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Input/Commands/KeypressInvoker.h
> +	/// A shared pointer to the command which needs to be registered
Is het niet een algemene standaard dat het in de .cpp komt?
Tenzij er geen .cpp is natuurlijk

2020-12-10 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Input/Commands/Engine/ToggleFpsCommand.h
> +class ToggleFpsCommand : public ICommand
Doxygen

2020-12-10 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/General/ISubsystem.h
> +/// </summary>
Verkeerde doxygen manier.
Copy paste foutje?

2020-12-10 10:54 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.cpp
> +	// TODO inventory commands
Wordt volgens mij ATM gedaan maar dan moet dit wel ff weg.

2020-12-11 16:19 UTC, ttleeuw commented on Glitch/Game/Commands/Builder/CommandBuilder.cpp
> +#include <Game\Commands\GlobalCommands\ToggleLayerCommand.h>
consistency

2020-12-11 16:19 UTC, ttleeuw commented on Glitch/Game/Commands/Builder/CommandBuilder.cpp
> +		{ KeyCode::KEY_A, "moveLeft" },
Even kijken, credits heeft pijltje links/rechts sneller gaan. Zou het niet omschrijven naar commands maar wel afdwingen

2020-12-11 16:22 UTC, ttleeuw commented on Glitch/Game/Commands/Creator/UICommands/UICommandFactory.h
> +class UICommandFactory
misschien toch generic?

2020-12-12 15:12 UTC, wieltar commented on Glitch/Game/Commands/Builder/CommandBuilder.cpp
> +		{ KeyCode::KEY_A, "moveLeft" },
hoe bedoel je dat precies?

2020-12-12 20:35 UTC, Rinkeeee96 requested changes
Hij crasht als je de inventory afsluit

2020-12-14 10:13 UTC, Rinkeeee96 approved these changes

2020-12-14 10:19 UTC, WilliamRossAvans approved these changes

2020-12-14 10:34 UTC, TheLarsJansen approved these changes

2020-12-14 10:34 UTC, merged

2020-12-14 10:34 UTC, ttleeuw approved these changes