[WIP] Better saving loading
Rinkeeee96/FoxTrot_SA_Engine pull request #120
Opened 2020-11-30 13:28 UTC by Rinkeeee96

2020-12-04 09:26 UTC, ttleeuw commented on Glitch/Game/Game.cpp
> +	savegame = new Savegame();
pointer?

2020-12-04 09:27 UTC, ttleeuw commented on Glitch/Game/Game.h
> +	shared_ptr<SceneStateMachine> stateMachine;
shared pointer, unique pointer?

2020-12-04 09:28 UTC, ttleeuw commented on Glitch/Game/SaveGame/Savegame.h
> +#define MAX_AMOUNT_OF_LEVELS 3
todo dat dit aangepast moet worden met nieuwe levels?

2020-12-04 09:29 UTC, ttleeuw commented on Glitch/Game/Scenes/GameScene.cpp
> +void GameScene::registerSavegame(Savegame * _savegame)
pointer?

2020-12-04 09:34 UTC, ttleeuw commented
Iets meer info over save game in save menu;
- laatst gespeeld?
- het level dat die is?

2020-12-04 14:13 UTC, TheLarsJansen reviewed
Best veel files changed maar ziet er verder wel goed uit.
3 Kleine dingen moet je ff naar kijken.
Als die resolved zijn is het prima

2020-12-04 14:13 UTC, TheLarsJansen commented on Glitch/Game/SaveGame/Savegame.cpp
> +		// File doesnt exist.
Moet hier iets mee gebeuren?

2020-12-04 14:13 UTC, TheLarsJansen commented on Glitch/Game/Scenes/GameScene.h
> +	shared_ptr<Savegame> savegame;
Mooi dat dit nu shared ptr is! 👍

2020-12-04 14:13 UTC, TheLarsJansen commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
> +	save3->setPositionX(CENTER_X - save3->getWidth() / 2 - 110);
Magic numbers

2020-12-04 14:31 UTC, ttleeuw commented on Glitch/Game/Game.h
> +	shared_ptr<Savegame> savegame;
Kan dit geen unique pointer worden? Of gewoon SaveGame en als reference doorgeven?

2020-12-04 14:31 UTC, ttleeuw commented on Glitch/Game/Game.h
> +	shared_ptr<SceneStateMachine> stateMachine;
Kan dit geen unique pointer worden? Of gewoon SaveGame en als reference doorgeven?

2020-12-04 14:31 UTC, wieltar requested changes

2020-12-04 14:31 UTC, wieltar commented on Glitch/Game/SaveGame/Savegame.h
> +#define MAX_AMOUNT_OF_LEVELS 3
Kan je dit niet in general defines plaatsen?

2020-12-04 14:31 UTC, wieltar commented on Glitch/Game/SaveGame/Savegame.h
> +		if (saveGameDataMap.count(id) > 0)
je kan direct de (saveGameDataMap.count(id) > 0) returnen, dit evaluate naar een bool

2020-12-04 14:31 UTC, wieltar commented on Glitch/Game/SaveGame/Savegame.h
> +		if (saveGameDataMap.count(id) > 0)
Je kan hier je isempty functie gebruiken

2020-12-04 14:31 UTC, wieltar commented on Glitch/Game/Scenes/Overworld/Overworld.cpp
> +	auto* level1TextBtn = new Button(2, ColoredText("Level 1, Score: " + to_string(savegame->getCurrentGameData().levelData[0].score), Color(0, 0, 0)), BIND_FN(onLevel1BtnClick), transSprite, this->disp
kan je de lijn to_string(savegame->getCurrentGameData().levelData[0].score) abstraheren naar een variable?
Dat maakt het wat leesbaarder. of nog mooier i.c.m bijvoorbeeld een functie die de gegevens van je level ophaalt aan de hand van je levelnummer

2020-12-04 14:31 UTC, wieltar commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
>  {
Ik zie hier heel veel duplicate code en gedrag voor de 3 saves, je zou dit kunnen plaatsen in een bepaalde button die dit gedrag voor je regelt

2020-12-04 14:31 UTC, wieltar commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
> +		SaveGameData save3;
volgens mij was dit een ctrl+c ctrl+v aangezien ik dit meerdere keren terug zie komen in de andere functies ;)

2020-12-04 14:31 UTC, wieltar commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +void GeneralTransition::start(bool playSound)
iets vreemds dat me opvalt als ik van overworld naar main menu ga dan begint de muziek opnieuw, ik weet niet zo goed waar dit vandaan komt dus ik zet het maar even hierbij :)

2020-12-04 14:34 UTC, wieltar commented on Glitch/Game/SaveGame/Savegame.cpp
> +		// File doesnt exist.
is mij ook niet helemaal duidelijk

2020-12-04 14:34 UTC, ttleeuw commented on Glitch/Game/Scenes/GameScene.h
> +	shared_ptr<Savegame> savegame;
Zou dit geen reference moeten zijn, nu "beheren" twee klassen savegame

2020-12-04 14:35 UTC, ttleeuw commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
> +	auto* save1 = new PrimaryButton(-996, nameBtn, BIND_FN(onSave1BtnClick), this->dispatcher);
Aparte functie? Gebeurd best veel en nummers lijken enigszins hetzelfde

2020-12-04 14:36 UTC, ttleeuw commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
> +	if (savegame->isSaveGameDataEmpty(2))
aparte functie, veel herhaling

2020-12-04 14:36 UTC, ttleeuw commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
> +	if (savegame->isSaveGameDataEmpty(3))
aparte functie, veel herhaling

2020-12-04 14:36 UTC, ttleeuw commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
> +	if (savegame->isSaveGameDataEmpty(1))
aparte functie, veel herhaling

2020-12-04 14:37 UTC, ttleeuw commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.h
> +	SceneStateMachine(Engine& engine, shared_ptr<Savegame> savegame);
Wel sharedpointer? ivm beheer?

2020-12-04 14:37 UTC, ttleeuw commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.cpp
> +SceneStateMachine::SceneStateMachine(Engine& _engine, shared_ptr<Savegame> _savegame) : engine(_engine), savegame(_savegame)
Wel sharedpointer? ivm beheer?

2020-12-04 14:52 UTC, ttleeuw reviewed
Doxygen

2020-12-04 15:38 UTC, Rinkeeee96 commented on Glitch/Game/SaveGame/Savegame.cpp
> +		// File doesnt exist.
is gwn uitleg waarom er niks in die catch gebeurt

2020-12-04 15:38 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/SaveScreen/SaveScreen.cpp
> +	save3->setPositionX(CENTER_X - save3->getWidth() / 2 - 110);
Is overal al zo dus ga ik niet aanpassen

2020-12-04 15:40 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Overworld/Overworld.cpp
> +	auto* level1TextBtn = new Button(2, ColoredText("Level 1, Score: " + to_string(savegame->getCurrentGameData().levelData[0].score), Color(0, 0, 0)), BIND_FN(onLevel1BtnClick), transSprite, this->disp
Geprobeerd maar ivm de functie pointer werkt dat niet lekker

2020-12-04 15:41 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +void GeneralTransition::start(bool playSound)
Dat is overal zo en altijd geweest

2020-12-05 11:36 UTC, ttleeuw approved these changes
Code niks meer op aan te merken,
Qua functionaliteit een ding dat me opviel;
- Score zichtbaar bij levels alleen wordt nog niks meegedaan, misschien kan deze weg?

2020-12-06 12:43 UTC, wieltar approved these changes

2020-12-06 12:44 UTC, WilliamRossAvans approved these changes

2020-12-06 12:45 UTC, merged