[W.I.P] Enemy/NPC animations
Rinkeeee96/FoxTrot_SA_Engine pull request #124
Opened 2020-12-02 16:19 UTC by Maxvani

2020-12-04 09:24 UTC, ttleeuw commented on engineFoxtrot/Engine/Events/Action/ObjectStopEvent.h
> +	const bool GetStopVertical() const { return stopVertical; }
camel

2020-12-04 09:25 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +	physicsFacade->stopObject(e.GetObjectId(), e.GetStopVertical());
camel

2020-12-04 14:26 UTC, TheLarsJansen reviewed
Paar kleine dingen.
Ziet er verder wel prima uit volgens mij

2020-12-04 14:26 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Slime.h
>  	void onUpdate() override {
Volgens mij is het niet persee uit deze pr, maar de implementatie moet wel in de .cpp

2020-12-04 14:26 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Slime.h
> +		bool playerIsOnSameXLvl = (slimeMiddleX >= player->getPositionX()) && (slimeMiddleX <= (player->getPositionX() + player->getWidth()));
Vind deze namen een beetje misleidend.
Dacht dat de playerIsBelowMe echt keek naar of de player onder de slime stond en daardoor snapte ik de playerIsOnSameXLvl niet. Miss iets anders noemen naar playerIsLowerThenSlime en playerIsWithXRange ofzo

2020-12-04 14:26 UTC, TheLarsJansen commented on Glitch/Game/Characters/Player/Player.h
> +#define PLAYER_SPRITE_HEIGHT 37
Willen we dit hardcoded hebben?

2020-12-04 14:26 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Slime.h
>  	void onUpdate() override {
Geldt ook voor de andere character klassen

2020-12-04 14:28 UTC, TheLarsJansen commented
Zitten wel nog warnings in die je moet fixen

2020-12-04 14:43 UTC, ttleeuw commented on Glitch/Game/Characters/Player/Player.h
> +#define PLAYER_SPRITE_HEIGHT 37
Staat volgens mij al sinds het begin zo en nooit iets aan gedaan

2020-12-04 14:47 UTC, Maxvani commented on Glitch/Game/Characters/Player/Player.h
> +#define PLAYER_SPRITE_HEIGHT 37
Staat nu voor iedere sprite voor ieder object hard-coded, misschien wel een goeie idd om hem automatisch naar de sprite grootte te laten kijken

2020-12-04 14:53 UTC, ttleeuw reviewed
Doxygen

2020-12-06 12:31 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +#define JUMP_ANIMATION_TIME 100
Naar algemene general defines?

2020-12-06 12:32 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Slime.cpp
> +		if (jumpTimer == JUMP_ANIMATION_TIME / 2) {
Dit kan ifelse zijn?

2020-12-06 12:33 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +		if (jumpTimer == JUMP_ANIMATION_TIME / 2) {
If else

2020-12-06 12:33 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Player/Player.h
> +#define PLAYER_SPRITE_HEIGHT 37
Verplaatsen naar general defines

2020-12-06 12:34 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/General/Debug.h
> +#define DEBUG_MAIN true
Nogmaals. niet naar develop.. Op je vorige PRs ook al gezegd

2020-12-06 13:11 UTC, wieltar requested changes

2020-12-06 13:11 UTC, wieltar commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +		if (jumpTimer == JUMP_ANIMATION_TIME / 2) {
of indien mogelijk een switch als niet elke conditie elke loop gecontroleerd moet worden

2020-12-06 13:11 UTC, wieltar commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +		if (jumpTimer == JUMP_ANIMATION_TIME / 2) {
een state machine zou natuurlijk ideaal zijn, dan zou je gelijke acties bij dezelfde states kunnen onderbrengen maar ik snap ook dat dat nu niet echt meer haalbaar is

2020-12-06 13:11 UTC, wieltar commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +	auto jumpkinDefault = new SpriteObject(textureId++, 43, 32, 1, 200, "Assets/Sprites/Enemies/Jumpkin/Jumpkin_idle.png");
Dit geldt voor meerdere sprite declaraties maar je hebt hier heel veel gelijke waarden, deze kan je denk ik net zo goed inline/met variablen declareren omdat de parameters nu heel foutgevoellig zijn

2020-12-06 13:11 UTC, wieltar commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +	auto jumpkinDefault = new SpriteObject(textureId++, 43, 32, 1, 200, "Assets/Sprites/Enemies/Jumpkin/Jumpkin_idle.png");
of zelfs een standaard file conventie die overeen komt met de enums 
bijv.
slime/jump.png
slime/walk_left_num.png
jumpkin/walk_left_num.png

Dat maakt het uitlezen heel simpel en als er een foute animatie is weet je dat je bij de bestanden moet gaan kijken

2020-12-06 13:11 UTC, wieltar commented on Glitch/Game/Characters/Player/Player.h
> +#define PLAYER_SPRITE_HEIGHT 37
ik zie hier nu dat je inderdaad een define gebruikt voor sprites, (zie mijn eerdere comments) is wel een mooi voorbeeld van een extra refactor dingetje om dit gelijk te trekken bij elke sprite/karakter

2020-12-06 13:11 UTC, wieltar commented on Glitch/Game/Factories/CharacterFactory.cpp
> +void CharacterFactory::registerCharacter(string name, ICharacter* character, int* textureID) {
ik weet niet zo goed waarom je een primitive als pointer wil, zou je dit kunnen toelichten?

2020-12-06 13:11 UTC, wieltar commented on Glitch/Game/SpriteState.h
> +	ACTION_LEFT_1,
zoals eerder toegelicht zou het heel mooi zijn als je deze enumeratoren kan gebruiken in de bestandsnamen, maakt het registreren van acties misschien wat makklijker

2020-12-07 09:00 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +#define JUMP_ANIMATION_TIME 100
Dit is enemy specifiek

2020-12-07 09:00 UTC, Maxvani commented on engineFoxtrot/Engine/General/Debug.h
> +#define DEBUG_MAIN true
Hij is nog W.I.P hè ;)

2020-12-08 14:23 UTC, WilliamRossAvans submitted a review, later dismissed

2020-12-08 14:23 UTC, WilliamRossAvans commented on Glitch/Game/Characters/Enemies/Fleye.cpp
> +	bool playerIsInRange = (diff < RANGE&& diff >(RANGE * -1));
graag veranderen naar < RANGE && diff (spatie)

2020-12-08 14:23 UTC, WilliamRossAvans commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +	bool playerIsInRangeVertically = (yDiff < VERTICAL_RANGE&& yDiff >(VERTICAL_RANGE * -1));
Gebruik hier de stelling van pitagoras, dat is een echtere range dan horizontal en vertical

2020-12-08 14:45 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +	bool playerIsInRangeVertically = (yDiff < VERTICAL_RANGE&& yDiff >(VERTICAL_RANGE * -1));
Pythagoras ;) maar goeie

2020-12-08 14:57 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +	bool playerIsInRangeVertically = (yDiff < VERTICAL_RANGE&& yDiff >(VERTICAL_RANGE * -1));
Het probleem hier is dat als je de enemy een range geeft dan geldt deze range zowel voor horizontaal als voor verticaal. Dit houdt in dat in bijvoorbeeld level 3 de Jumpkin al horizontaal naar je toe gaat springen als je op het platform eronder staat.
Om deze reden heb ik dit zo bij de Jumpkin gedaan

2020-12-08 15:14 UTC, wieltar commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +	bool playerIsInRangeVertically = (yDiff < VERTICAL_RANGE&& yDiff >(VERTICAL_RANGE * -1));
konden we dan hier niet beter kijken naar de 'radar' van box2d? (het is dat ik daar nu aan denk omdat ik weet dat andere groepen dat zo deden)

2020-12-08 15:29 UTC, wieltar submitted a review, later dismissed

2020-12-08 15:54 UTC, TheLarsJansen requested changes

2020-12-08 15:54 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/BaseEnemy.h
> +#define SLIME_ACTION_SPRITE_HEIGHT 24
Dit is enemy specifiek

2020-12-08 15:54 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Fleye.cpp
> +	float diff = player->getPositionX() - this->getPositionX();
diff? Differential? Different? Diffy joe?

Misschien xDistance van maken ofzo?

2020-12-08 15:54 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/BaseEnemy.h
> +#define JUMP_ANIMATION_TIME 50
Dit is blijkbaar zie ik later specifiek voor de slime. Moet daarheen verplaatst worden.
Dacht eerst dat die universeel was voor de slime en jumpkin maar dat is dus niet zo. 
Ook de naam ff slime specifiek maken.

2020-12-08 15:54 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +		if (jumpTimer == JUMPKIN_JUMP_ANIMATION_TIME / 2) {
Verander je met het aanpassen van de JUMP_TIME define ook de jump hoogte?
Of is dat een beetje losse vinger werk over hoelang de slime in de lucht hangt en dat je dan daar de animaties op aanpast

2020-12-08 15:54 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Slime.cpp
> +		if (jumpTimer < SLIME_JUMP_ANIMATION_TIME / 2) {
Zelfde als bij jumpkin animation time.
Volgens mij heb ik daar slime gezegt. Naja is vast wel te begrijpen

2020-12-08 15:54 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Slime.cpp
> +		jumping = true;
Als je hier jumping op true zet zal de if op regel 18 meteen in gegaan worden.
Is dit de bedoeling? Just checking want dit is een veel gemaakte fout.

2020-12-08 15:54 UTC, TheLarsJansen commented on Glitch/Game/Factories/CharacterFactory.cpp
> +		*textureID += spriteMap.size();
Geeft een conversion warning.
Dit is makkelijk zelf te checken door het project te rebuilden en dan in de output window ff in de gaten te houden of er een warning wordt gethrowd

2020-12-08 16:16 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/BaseEnemy.cpp
> +	auto collisionEvent = static_cast<const OnCollisionBeginEvent&>(event);
Idk heb dit alleen verplaatst, zal het wel aanpassen

2020-12-08 16:17 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/BaseEnemy.h
> +#define SLIME_ACTION_SPRITE_HEIGHT 24
Lol kopie gemaakt van Slime en dit er niet uit gehaald, slecht I know

2020-12-08 16:24 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/BaseEnemy.h
> +#define JUMP_ANIMATION_TIME 50
Hehe whoops zelfde als hierboven erg slecht dat ik dat niet heb gezien

2020-12-08 16:26 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +		if (jumpTimer == JUMPKIN_JUMP_ANIMATION_TIME / 2) {
De sprite veranderd midair niet, dus deze veranderd alleen bij het "chargen" vóór de jump en dus ook weer wanneer de slime op de grond staat. JumpHeight maakt hier dus niet uit. Zelfde geldt hieronder vd slime

2020-12-08 16:27 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/Slime.cpp
> +		jumping = true;
Ja dit klopt. De timer van het jumpen kan dan meteen worden aangepast

2020-12-08 16:47 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/BaseEnemy.cpp
> +		if (collisionEvent.getObjectOne().getObjectId() == this->getObjectId()) {
Misschien niet aan jou ivm dat het er al op stond, maar lostrekken in aparte functie -> getCollidedEntity

2020-12-08 16:56 UTC, wieltar approved these changes

2020-12-09 09:11 UTC, Rinkeeee96 submitted a review, later dismissed

2020-12-09 16:15 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/General/Debug.h
> +#define DEBUG_MAIN true
Pas je deze nogmaals aan?

2020-12-09 16:16 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	PhysicsEngine(FrameData& _frameData) : frameData{ _frameData } {};
Dit hoort helemaal niet in deze pr?

2020-12-09 16:19 UTC, Rinkeeee96 submitted a review, later dismissed
Develop mergen, fps changes eruit. Debug main weg. Even goed kijken voordat je zegt dat je PR "goed" is

2020-12-09 17:51 UTC, Rinkeeee96 commented on Glitch/Game/SpriteState.h
> +	ACTION_LEFT_1,
Is dit nog gebeurt?

2020-12-10 08:41 UTC, WilliamRossAvans approved these changes

2020-12-10 13:07 UTC, TheLarsJansen requested changes
Doe nog even een doxygen rondje.
Dan vind ik hem mooi.
Doe ff review requesten als je klaar bent.

2020-12-10 13:07 UTC, TheLarsJansen commented on Glitch/Game/Characters/Player/Player.h
Doxygen

2020-12-10 15:22 UTC, TheLarsJansen requested changes

2020-12-10 15:22 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Fleye.cpp
> +	// Calculates if the enemy is in range of the player
Dit is geen doxygen.
Dit zijn normale comments die worden genegeerd door doxygen

2020-12-10 15:32 UTC, TheLarsJansen submitted a review, later dismissed
Voor de volgende keer dus Doxygen in de CPP zetten 👍

2020-12-10 15:42 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Fleye.cpp
> +map<SpriteState, SpriteObject*> Fleye::buildSpritemap(int textureId) {
Doxygen?

2020-12-10 15:42 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Fleye.cpp
> +void Fleye::onUpdate() {
Doxygen?

2020-12-10 18:14 UTC, TheLarsJansen approved these changes

2020-12-10 19:20 UTC, Rinkeeee96 approved these changes

2020-12-11 07:50 UTC, ttleeuw approved these changes

2020-12-11 07:59 UTC, merged