[WIP] Pause screen
Rinkeeee96/FoxTrot_SA_Engine pull request #125
Opened 2020-12-03 09:26 UTC by TheLarsJansen

2020-12-03 15:09 UTC, TheLarsJansen commented
Text is of center, weet ik, wordt nog gefixt

2020-12-03 15:15 UTC, Maxvani commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	void setPhysicsPause(bool value) { physicsPaused = value; };
Moet dit niet setPhysicsPauseD zijn? ;)

2020-12-03 15:17 UTC, Maxvani commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	// Get highest zIndex
Misschien een functie van maken?

2020-12-03 15:18 UTC, Maxvani commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +		for (auto layer : layers) {
Functie van maken zodat dit herbruikt kan worden (zie comment hierboven)

2020-12-03 15:22 UTC, Maxvani commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +			createPopUpLayer(WINDOW_WIDTH_CENTER, WINDOW_HEIGHT_CENTER, "Paused");
Misschien beter om net als bij de scenes een generieke popup te maken die hier aan mee kan geven. Zo kun je bijvoorbeeld een text popup hebben zoals deze, maar ook een popup met een afbeelding en text of zelfs knoppen

2020-12-03 15:28 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	void setPhysicsPause(bool value) { physicsPaused = value; };
Kan private

2020-12-04 14:44 UTC, TheLarsJansen commented on Glitch/Game/Scenes/DeathScreen/DeathScreen.cpp
> +	stateMachine.switchToScene(stateMachine.getCurrentSceneIdentifier(), true);
Dit is een fix vanuit level2/3 die ik gecherrypicked heb zodat ik die fix had

2020-12-04 14:44 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Engine.cpp
> +	if (!getPhysicsPaused()) {
Dit moet dus nog anders gaan als de command pattern erin zit. Ik wil dan na het indrukken van de P een event afvuren die op meerdere plekker geluister wordt en dus dan per systeem op pauze zet. Hoe ik het nu doe is best lomp

2020-12-04 14:44 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +bool PhysicsEngine::onKeyPressed(const Event& event) {
Dit gaat weg als command pattern erin zit

2020-12-04 14:44 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +bool Scene::onKeyPressed(const Event& event) {
Dit gaat weg als command pattern erin zit

2020-12-04 14:44 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::removePopUpLayer() {
Op dit moment kunnen we maar 1 popUp layer hebben. Als we er meer willen hebben moet ik dit op een andere manier bij houden. Laat even weten wat jullie willen

2020-12-04 14:53 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	void setPhysicsPause(bool value) { physicsPaused = value; };
Ja maar een private setter is beetje nutteloos. Heb deze gemaakt voor als command pattern erin zit. Weet niet zeker of ik hem dan ga gebruiken maar die haal ik er dan wel uit

2020-12-04 14:54 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +bool Scene::onKeyPressed(const Event& event) {
Add // TODO?

2020-12-04 14:55 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +bool PhysicsEngine::onKeyPressed(const Event& event) {
Add // TODO?

2020-12-04 14:55 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.cpp
> +	if (!getPhysicsPaused()) {
Add // TODO?

2020-12-04 14:58 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::removePopUpLayer() {
Een is genoeg denk ik?

2020-12-04 14:59 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	layers.erase(zIndex);
stel je hebt geen hasActivePopUp = false, verwijder je dan geen bestaande?

2020-12-04 14:59 UTC, ttleeuw reviewed
Doxygen

2020-12-04 15:00 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::removePopUpLayer() {
lijkt mij op zich geen ramp, we willen 9/10 keer geen meerdere popups tegelijkertijd laten zien op dit moment, wat je zou kunnen doen is bepaalde lagen klaarzetten maar niet tonen, deze bovenaan plaatsen on keypress en dan als je klaar bent weer weghalen.

Dan kan je de popup's als laag behandelen, de identifier teruggeven en als je dan 1 specifieke popup weg wil halen geef je gewoon het id mee dat je terug hebt gekregen van de functie

2020-12-04 15:01 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::removePopUpLayer() {
we moeten dan wel de scenemanger zelf zijn id's laten regelen denk ik

2020-12-04 15:02 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	layers.erase(zIndex);
Ja goede moet in de if

2020-12-04 15:02 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	layers.erase(zIndex);
Of er moet ff een return bij. Ga het fixen

2020-12-04 15:11 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.cpp
> +	if (!getPhysicsPaused()) {
Deze check wordt ook in de physicsEngine uitgevoerd?

2020-12-04 15:12 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.h
> +	bool getPhysicsPaused();
Beter algeheel paused gebruiken? Zodat de engine aan de hand daarvan dingen update ja of de nee?

2020-12-04 15:13 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +	if (!getPhysicsPaused()) {
Zie opmerking -> engine getPhysicsPaused

2020-12-04 15:14 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +/// @brief Extended PopUp creation
popup zonder text?

2020-12-04 15:15 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Engine.h
> +	bool getPhysicsPaused();
Ja goede, beetje slordig van me. Wou hem voor de VrijMiBo erin hebben hahaha.
Haast en spoed is zelden goed

2020-12-04 15:15 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::removePopUpLayer() {
Het is geen ramp, maar denk niet dat het geimplementeerd hoeft te worden KISS;
https://en.wikipedia.org/wiki/KISS_principle

2020-12-04 15:16 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +/// @brief Extended PopUp creation
Jaa is voor help scherm bijv. doe je alleen een spriteobject laten zien.

2020-12-04 15:19 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.h
> +	bool getPhysicsPaused();
Bijna weekend

2020-12-04 15:22 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Engine.h
> +	bool getPhysicsPaused();
Oh wacht nee niet slordig
Dit had ik zo gedaan want ik kan in de engine niet naar een event luisteren
Of iig subscriben want ze bestaan dan nog niet

2020-12-04 15:23 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Engine.h
> +	bool getPhysicsPaused();
Opgelost

2020-12-04 15:25 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::removePopUpLayer() {
KEEP IT STUPID SIMPLE 😄

2020-12-04 15:33 UTC, ttleeuw submitted a review, later dismissed

2020-12-04 15:39 UTC, wieltar approved these changes

2020-12-04 16:06 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.h
> +	string& getCurrentSceneIdentifier();
Dubbel?

2020-12-04 16:07 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +	if ((currentSceneID != (*pointerToCurrentScene)->getSceneID()))
Waarom extra haakjes?

2020-12-04 16:08 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +
Doxygen

2020-12-04 16:09 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::removePopUpLayer() {
@wieltar Die functionaliteit zit er al ergens in volgensmij

2020-12-05 09:18 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Statemachine/SceneStateMachine.h
> +	string& getCurrentSceneIdentifier();
Merge foutjeeee....

2020-12-05 11:31 UTC, ttleeuw submitted a review, later dismissed
Enige ding en het wordt wss een issue;
- De onupdate van een scene wordt niet meegenomen (credits blijven doorrollen, transitie blijft doorgaan)

2020-12-06 12:47 UTC, wieltar submitted a review, later dismissed
code wat opgeschoond, ziet er goed uit, het enige is inderdaad dat niet overal de juiste onupdates worden gebruikt, hier moeten we even naar kijken met het command pattern later

2020-12-06 12:53 UTC, wieltar submitted a review, later dismissed

2020-12-06 12:54 UTC, WilliamRossAvans requested changes

2020-12-06 12:54 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	int zIndex = getHighestLayerIndex() + 2;
Heel klein dingetje, waarom +2 en niet gewoon +1

2020-12-06 12:54 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	PopUp* popUp3 = new PopUp(-6487, width, height, (xPosition - width / 2), (yPosition + height / 2), ColoredText(text, Color(0, 0, 0)));
Popup3 word nergens meer gebruikt

2020-12-06 15:23 UTC, Rinkeeee96 approved these changes

2020-12-06 16:16 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	int zIndex = getHighestLayerIndex() + 2;
Gewoon voor de safe. Defensive programming

2020-12-06 16:16 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	PopUp* popUp3 = new PopUp(-6487, width, height, (xPosition - width / 2), (yPosition + height / 2), ColoredText(text, Color(0, 0, 0)));
Goede, had ik voor de tests er ff in staan en vergeten weg te halen

2020-12-06 18:17 UTC, merged