[W.I.P] Json validation
Rinkeeee96/FoxTrot_SA_Engine pull request #129
Opened 2020-12-07 12:02 UTC by WilliamRossAvans

Doxygen moet nog toegevoegd worden

2020-12-08 08:31 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.cpp
> +using valijson::Schema;
Dit niet doen, externe libraries, nu niet in een oog opzicht te zien waar 3rd party libraries worden gebruiken

2020-12-08 08:32 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.cpp
> +void LoadLevelFacade::validateLevel(string path) {
aparte parser/validator klassen

2020-12-08 08:33 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.h
> +	void validateLevel(string path);
void, geen true or false? verwacht ik wel met valideren is valide ja/nee

2020-12-08 08:36 UTC, ttleeuw reviewed
Misschien 3rd party libraries aparte PR?

Waarom twee libraries, is er geen 1 die beide oplost, afhankelijk zijn van 2 libraries is niet ideaal

2020-12-08 14:17 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.cpp
> +	bool validLevel = fileLoader.validateJSON(path, "Game/Levels/level-validation-schema.json");
Zou het niet in fileloader doen maar aparte klassen;
IValidator

JsonValidator : IValidator

2020-12-08 14:18 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.cpp
> +	bool validLevel = fileLoader.validateJSON(path, "Game/Levels/level-validation-schema.json");
Kan waarschijnlijk wel in de engine

2020-12-08 14:19 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.cpp
> +	bool validLevel = fileLoader.validateJSON(path, "Game/Levels/level-validation-schema.json");
Zou eerst openen en dan pas valideren

2020-12-08 14:19 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.h
> +	void validateLevel(string path);
Kan deze nu niet weg?

2020-12-08 16:03 UTC, TheLarsJansen approved these changes

2020-12-08 16:03 UTC, TheLarsJansen commented on engineFoxtrot/Engine/FileParser/FileLoader.cpp
> +bool FileLoader::validateDocument(string path, string validationPath) {
Ik denk dat het wel netjes is als deze wordt losgetrokken naar een eigen class.
Hiermee houd je het laden van het bestand verantwoordelijk voor het laden.
En dan maak je een fileChecker die controleert of het wel een valid bestand is.

2020-12-08 16:03 UTC, TheLarsJansen commented on engineFoxtrot/Engine/FileParser/FileLoader.cpp
> +bool FileLoader::validateDocument(string path, string validationPath) {
Oh huh wacht, niks gezegd. JsonValidator is de aparte class waar ik het over had.
Ik moet ff mijn ogen open doen...

2020-12-08 16:04 UTC, TheLarsJansen requested changes
Eerst ff warnings fixen. Dan is die goed

2020-12-08 16:33 UTC, wieltar approved these changes

2020-12-08 16:33 UTC, wieltar commented on engineFoxtrot/Engine/FileParser/JsonValidator.cpp
> +JsonValidator::JsonValidator(string path, string validationPath) : IFileValidator(path, validationPath) {
Het was me niet 1..2..3 duidelijk waar ik mijn validation file toe moest voegen, zou je dit kunnen documenteren met doxygen en/of anders de variablen namen aan kunnen passen?

Verder top dat je dit hebt opgesplitst!!

2020-12-08 16:34 UTC, wieltar requested changes
de vorige moest een request changes zijn

2020-12-09 08:44 UTC, Rinkeeee96 approved these changes

2020-12-09 09:05 UTC, ttleeuw approved these changes

2020-12-09 09:16 UTC, TheLarsJansen approved these changes

2020-12-09 09:17 UTC, wieltar approved these changes

2020-12-09 09:18 UTC, merged