Feature/cheats
Rinkeeee96/FoxTrot_SA_Engine pull request #131
Opened 2020-12-07 13:33 UTC by ttleeuw

Press G for god mode 

Buffer timer when hit of 2 seconds

2020-12-08 14:08 UTC, WilliamRossAvans requested changes
Mis nog een duidelijke inidcator dat je in godmode staat, functionaliteit is overgens wel goed.

2020-12-08 14:22 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +		this->damage = 1;
Klopt maar wel overzichtelijker voor degene die het gebruikt om niet de default te gebruiken

2020-12-08 14:22 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +		this->damage = 1;
Klopt maar wel overzichtelijker voor degene die het gebruikt om niet de default te gebruiken

2020-12-08 14:22 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Slime.h
> +		this->damage = 1;
Klopt maar wel overzichtelijker voor degene die het gebruikt om niet de default te gebruiken

2020-12-08 14:23 UTC, ttleeuw commented on Glitch/Game/Characters/ICharacter.h
> +	bool canHit = true;
canHit is voor bv de timeout als je gehit wordt

2020-12-08 14:38 UTC, TheLarsJansen commented on Glitch/Game/Characters/Player/Player.h
> +
Beetje miereneneukerij maar zijn die enters nodig? 
Vervuilt de PR een beetje

2020-12-08 14:38 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.cpp
> +		else this->player->getStateMachine().setCurrentState(new NormalState, this->player);
Dit is echt een rete lang if
ff opsplisten naar meerdere regels.
Dus:
if(.......){
      bla bla;
} else{
     bla bla;
}

Maakt het wat overzichtelijker

2020-12-08 14:38 UTC, TheLarsJansen commented on Glitch/Game/States/Player/InvinsibleState.h
> +class InvinsibleState : public IState<Player>
Als ik deze state zie zou ik denken dat de Speler knippert ofzo als die damage krijgt maar dat zie ik niet gebeuren.
Waar wordt deze state voor gebruikt?

2020-12-08 14:43 UTC, ttleeuw commented on Glitch/Game/States/Player/InvinsibleState.h
> +class InvinsibleState : public IState<Player>
Timer dat de player geen damage kan krijgen, daarna weer op normaal gezet

2020-12-08 15:48 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/IEnemy.h
> +	void doDamage() { this->player->removeHealth(this->damage); }
Misschien wat generieker maken, dus dat je een object meegeeft om damage aan te doen stel we zouden bijvoorbeeld willen dat sommige enemies elkaar aan kunnen vallen (toekomstgericht etc.)
Je zou dan deze functie nog steeds alleen kunnen aanroepen op collision met de player, maar dan handel je meteen uitzonderingen af

2020-12-08 15:53 UTC, Maxvani commented on Glitch/Game/States/Player/InvinsibleState.cpp
> +void InvinsibleState::entry(Player* entity) {
Invincible*

2020-12-08 15:54 UTC, Maxvani commented on Glitch/Game/States/Player/InvinsibleState.cpp
> +void InvinsibleState::entry(Player* entity) {
Invincible* Maar ik denk dat dit beter iets van DamageCooldownState kan heten of iets in die richting

2020-12-08 15:55 UTC, Maxvani commented on Glitch/Game/States/Player/InvinsibleState.h
> +class InvinsibleState : public IState<Player>
Vgm is dit voor als je gehit wordt dat je dan tijdelijk invincible bent. Ik zou het dan renamed naar iets van DamageCooldownState (zie comment hierboven)

2020-12-08 15:58 UTC, Maxvani commented on Glitch/Game/States/StateMachine.h
> +class StateMachine
Misschien dat ik nu aan het zeuren bent, maar een betere naam zou misschien EntityStateMachine of ObjectStateMachine zijn

2020-12-08 16:02 UTC, ttleeuw commented on Glitch/Game/States/StateMachine.h
> +class StateMachine
Met deze ben ik het niet mee eens, is niet specifiek voor een entity of een object, het is een generic statemachine

2020-12-08 16:04 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/IEnemy.h
> +	void doDamage() { this->player->removeHealth(this->damage); }
Weet niet of we dit willen doen?

2020-12-08 16:08 UTC, Maxvani commented on Glitch/Game/States/Player/GodState.cpp
> +void GodState::exit(Player* entity) {
Ik weet dat je in de NormaleState canHit weer op true zet, maar misschien net om hem hier ook al terug te zetten, dan garandeer je dat hij altijd teruggezet wordt

2020-12-08 16:10 UTC, Maxvani commented on Glitch/Game/States/StateMachine.h
> +class StateMachine
My bad

2020-12-08 16:19 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/IEnemy.h
> +	void doDamage() { this->player->removeHealth(this->damage); }
Zou het idd KISS houden. Eventueel een extra functie aanmaken waarbij dat kan.

2020-12-09 09:06 UTC, WilliamRossAvans approved these changes

2020-12-09 09:14 UTC, wieltar approved these changes

2020-12-09 09:14 UTC, Rinkeeee96 approved these changes

2020-12-09 09:14 UTC, merged