[WIP] feature/story/chapter-one
Rinkeeee96/FoxTrot_SA_Engine pull request #137
Opened 2020-12-09 07:55 UTC by ttleeuw

2020-12-09 13:09 UTC, TheLarsJansen approved these changes

2020-12-09 13:09 UTC, TheLarsJansen commented on Glitch/Assets/Levels/Story/ChapterOne.txt
> +Je kan Bob nog goed herinneren van de geweldige lessen die je op het Avans van hem hebt gehad.
het avans? de avans? avans?

2020-12-09 13:09 UTC, TheLarsJansen commented on Glitch/Assets/Levels/Story/ChapterOne.txt
> +Je vraag Bob wat er is gebeurd en zegt dat je je niks kan herrineren.
Je vraag Bob? vraagt Bob?

2020-12-09 13:09 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Story/ChapterOneScene.cpp
> +	SpriteObject* bg0 = new SpriteObject(-33, 1080, 1920, 1, 300, "Assets/Backgrounds/dark_bg.png");
bg0? bull green zero? heh?

2020-12-09 13:09 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Story/ChapterOneScene.cpp
> +	SpriteObject* fgB = new SpriteObject(-34, 1080, 1920, 1, 300, "Assets/Backgrounds/foreground_bottom.png");
fgB? KGB? Rusia?

2020-12-09 13:09 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Story/ChapterOneScene.cpp
> +	SpriteObject* fgT = new SpriteObject(-35, 1080, 1920, 1, 300, "Assets/Backgrounds/foreground_top.png");
fgT? for graties turbos? waar? wil ook wel turbo in mijn auto

2020-12-09 13:09 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Sound/SoundEngine.h
> +#define MAX_VOLUME 0
Euh? werkt dit?

2020-12-09 13:09 UTC, TheLarsJansen commented on engineFoxtrot/Engine/General/Debug.h
> +#define DEBUG_MAIN true
Als die op develop gaat moet deze terug naar false

2020-12-09 13:19 UTC, TheLarsJansen commented
WARNINGS :)

2020-12-09 16:04 UTC, WilliamRossAvans requested changes

2020-12-09 16:04 UTC, WilliamRossAvans commented on Glitch/Game/Scenes/Story/ChapterScene/ChapterScene.cpp
> +	auto startingId = 4;
Overnadenken, met wat er gebeurt bij meer objecten

2020-12-09 16:14 UTC, WilliamRossAvans approved these changes

2020-12-09 16:15 UTC, wieltar approved these changes

2020-12-09 16:25 UTC, wieltar submitted a review, later dismissed

2020-12-09 17:14 UTC, WilliamRossAvans requested changes
De max speed fixt het niet bij mij

2020-12-10 08:11 UTC, WilliamRossAvans submitted a review, later dismissed

2020-12-10 10:28 UTC, TheLarsJansen approved these changes

2020-12-10 12:59 UTC, Rinkeeee96 submitted a review, later dismissed

2020-12-10 13:03 UTC, TheLarsJansen submitted a review, later dismissed

2020-12-11 09:19 UTC, WilliamRossAvans approved these changes

2020-12-11 09:19 UTC, Rinkeeee96 approved these changes

2020-12-11 09:23 UTC, TheLarsJansen approved these changes

2020-12-11 09:23 UTC, merged