[W.I.P] DeltaTime
Rinkeeee96/FoxTrot_SA_Engine pull request #151
Opened 2020-12-11 10:54 UTC by Maxvani

2020-12-11 11:01 UTC, wieltar commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return TIMESTEP / lastFrameFps;
verschilt deze niet per subsystem?

2020-12-11 11:02 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +ParticleEngine::ParticleEngine(float* _deltaTime) : deltaTime{_deltaTime}
waarom is dit geen reference?

2020-12-11 11:02 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +			((ParticleAdapter*)particle)->update(*deltaTime);
je maakt van je pointer een ref? whut

2020-12-11 11:02 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.h
> +	ParticleEngine(float* deltaTime);
again ref?

2020-12-11 11:03 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return TIMESTEP / lastFrameFps;
In principe niet toch? Aangezien alles parallel loopt. Heb vgm ook nog nooit een DeltaTime gezien die over anders is

2020-12-11 11:04 UTC, wieltar commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return TIMESTEP / lastFrameFps;
Ik zou wel graag die flexibiliteit willen hebben om dit aan te kunnen passen

2020-12-11 11:05 UTC, wieltar commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return TIMESTEP / lastFrameFps;
laat ik het zo benoemen
in princiepe wil je je physics updaten op een constante rate maar niet zo snel als je renderer of whatever omdat deze dat niet zo vaak hoeft te doen
je renderer laat je unlocked of je geeft er vsync aan mee (vandaar die aanpasbaarheid) dus dan is het heel fijn als je een timestep kan meegeven aan de calculatie

2020-12-11 11:11 UTC, Maxvani commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +			((ParticleAdapter*)particle)->update(*deltaTime);
Volgens mij haal ik hier wat dingen door elkaar idd 😅

2020-12-11 11:15 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return TIMESTEP / lastFrameFps;
Maar dat doen we op het moment niet, dus is dat dan wel nodig?

2020-12-11 11:18 UTC, wieltar commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return TIMESTEP / lastFrameFps;
ja maar we hebben ook geen delta time implementatie gemaakt, ik zou gewoon zorgen dat het compleet is en dat we het uit elkaar kunnen trekken met multithreading zonder al teveel aanpassingen als we tijd over hebben

2020-12-11 13:52 UTC, Rinkeeee96 commented on Glitch/Assets/Savegame/saveGameData.json
> +{"savegames":[{"characterdata":null,"leveldata":[{"completed":false,"levelnr":0,"score":0},{"completed":false,"levelnr":1,"score":0},{"completed":false,"levelnr":2,"score":0}],"savegameid":1,"savegam
Dit hoeft niet gecommit te worden. Even weghalen plz

2020-12-11 13:53 UTC, Rinkeeee96 commented on Glitch/Game/Characters/Enemies/Jumpkin.h
> +#define JUMPKIN_JUMP_ANIMATION_TIME 2
Kan dit nu allemaal centraal bij elkaar gepakt worden? ff copy pasten naar een general enemy defines ofzo. Wat overzichtelijker en netter

2020-12-11 13:54 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Engine.cpp
> +	this->deltaTimePhysics = frameData.calculateDeltaTime(DELTATIME_TIMESTEP_PHYSICS);
Dit kan eventueel samen in 1 functie? Dan kun je zelf je timestep meegeven

2020-12-11 14:06 UTC, wieltar commented on engineFoxtrot/Engine/Engine.cpp
> +	this->deltaTimePhysics = frameData.calculateDeltaTime(DELTATIME_TIMESTEP_PHYSICS);
ik snap ook niet helemaal waarom je de deltatime voor je physics wrapped, in principe is het in de update van de physics genoeg

2020-12-11 15:11 UTC, Maxvani commented on Glitch/Assets/Savegame/saveGameData.json
> +{"savegames":[{"characterdata":null,"leveldata":[{"completed":false,"levelnr":0,"score":0},{"completed":false,"levelnr":1,"score":0},{"completed":false,"levelnr":2,"score":0}],"savegameid":1,"savegam
Misschien een idee om de GitIgnore te zetten?

2020-12-11 15:19 UTC, WilliamRossAvans requested changes

2020-12-11 15:19 UTC, WilliamRossAvans commented on Glitch/Game/Characters/Enemies/Jumpkin.cpp
> +void Jumpkin::onUpdate(float deltaTime) {
Update doxygen aangezien er een nieuwe parameter er bij is gekomen

Graag overal doen, dat scheelt een hoop comments ;)

2020-12-11 15:19 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +/// returns the current deltaTime (1 / fps of the last frame)
Add doxygen geef ook aan welke parameter je wilt ontvangen

2020-12-11 15:19 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +PhysicsEngine::PhysicsEngine(float& _deltaTime) : deltaTime{_deltaTime}
Doxygen, (controleer even alle functies)

2020-12-11 15:39 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	float& deltaTime;
Hier is het ook een reference?

2020-12-11 15:50 UTC, Maxvani commented on Glitch/Game/Characters/Enemies/Fleye.cpp
> +void Fleye::onUpdate(float deltaTime) {
Fleye heeft dit niet nodig omdat er niks qua timers enzo gebeurd. Physics heeft automatisch DeltaTime

2020-12-11 15:59 UTC, Maxvani commented on Glitch/Game/Scenes/WinScreen/WinScreen.cpp
> +		animation->setPositionY(animation->getPositionY() - deltaTime * 300);
Het is de bedoeling dat ze op elkaar reageren. Je moet namelijk eerst weten of je moet switchen van vallen/springen en daarna op basis daarvan omhoog of omlaag gaan

2020-12-11 15:59 UTC, Maxvani commented on Glitch/Game/Scenes/WinScreen/WinScreen.h
> +	bool falling = false;
Zie comment hierboven

2020-12-11 16:10 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Fleye.cpp
> +void Fleye::onUpdate(float deltaTime) {
Check

2020-12-11 16:18 UTC, wieltar requested changes
![afbeelding](https://user-images.githubusercontent.com/22468530/101927493-d950f880-3bd4-11eb-87a4-0adb5efafc96.png)
let op je conversies

2020-12-11 16:18 UTC, TheLarsJansen commented on Glitch/Game/Scenes/WinScreen/WinScreen.cpp
> +		animation->setPositionY(animation->getPositionY() - deltaTime * 300);
Okee duidelijk!

2020-12-11 16:23 UTC, TheLarsJansen commented
Ff die conversions en dan is die volgens mij wel goed

2020-12-11 16:26 UTC, Rinkeeee96 commented on Glitch/Assets/Savegame/saveGameData.json
> +{"savegames":[{"characterdata":null,"leveldata":[{"completed":false,"levelnr":0,"score":0},{"completed":false,"levelnr":1,"score":0},{"completed":false,"levelnr":2,"score":0}],"savegameid":1,"savegam
Haal deze er nogmaals even uit

2020-12-11 16:46 UTC, TheLarsJansen approved these changes

2020-12-11 16:47 UTC, TheLarsJansen commented
Zijn nog conflicten

2020-12-11 18:00 UTC, wieltar submitted a review, later dismissed
pauze werkt niet meer na je laatste merge met develop

2020-12-13 13:22 UTC, TheLarsJansen requested changes
Zoals wouter aangaf Pauze doet het niet meer. Inventory pauseert ook niet.

2020-12-13 13:28 UTC, TheLarsJansen approved these changes

2020-12-13 13:40 UTC, Rinkeeee96 approved these changes

2020-12-13 13:45 UTC, Rinkeeee96 requested changes
Winscherm animatie is weg
Transitie scherm gaat tesnel, beide balkje en animatie
Game loopt niet soepel? Speler voelt heel traag aan.

2020-12-13 13:54 UTC, Rinkeeee96 commented
Particles draaien ook een stuk langzamer dan develop

2020-12-15 12:43 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.h
> +	FrameData& frameData;
Unique ptr is netter

2020-12-15 12:44 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleLib/Particle.cpp
> +    deltaTime *= 2;
Dit is niet echt een manier van de snelheid van particles verhogen lijkt me?

2020-12-15 12:45 UTC, TheLarsJansen submitted a review, later dismissed
Bij het opstarten is de animatie van de speler niet te zien. Je krijgt hem pas te zien na 1 keer klikken.

2020-12-15 12:45 UTC, Maxvani commented on engineFoxtrot/Engine/ParticleSystem/ParticleLib/Particle.cpp
> +    deltaTime *= 2;
Wat moet ik dan doen, alle variabelen die deltaTime gebruiken *2 doen? Dit heeft hetzelfde effect

2020-12-15 12:46 UTC, Maxvani commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.h
> +	FrameData& frameData;
Dit is overal een reference, wordt hier meegestuurd vanuit engine. Kan er wel een shared pointer van maken in de engine, maar dan moet dat overal aangepast worden

2020-12-15 12:53 UTC, TheLarsJansen submitted a review, later dismissed

2020-12-15 13:11 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.h
> +	FrameData& frameData;
Unique ptr reference is netter.

2020-12-15 13:12 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleLib/Particle.cpp
> +    deltaTime *= 2;
Idk, moet een nettere manier zijn. Even in de groep gooien

2020-12-15 13:14 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.h
> +	FrameData& frameData;
Wat Rinke denk ik wil zeggen is dat bij het maken van de engine de FrameData als unique ptr gemaakt kan worden en dan de unique_ptr& meegegeven kan worden. Memory wise en qua C++ idioom is dat het mooist.

2020-12-15 13:59 UTC, Maxvani commented on engineFoxtrot/Engine/ParticleSystem/ParticleLib/Particle.cpp
> +    deltaTime *= 2;
DeltaTime is op basis van fps en is dus (bijna) altijd een getal lager dan 1. Om hier "normale" waardes uit te halen zul je dt moeten vermenigvuldigen. DeltaTime wordt hier met 2 vermenigvuldigd (alleen op deze plek) zodat alle particles met de juiste snelheid bewegen

2020-12-15 14:00 UTC, Maxvani commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.h
> +	FrameData& frameData;
Ah kijk dat is duidelijk

2020-12-15 14:01 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleLib/Particle.cpp
> +    deltaTime *= 2;
Ahh oke. Duidelijk. Vondt het alleen zo vreemd staan, maar snap de beredenering!

2020-12-15 14:05 UTC, TheLarsJansen approved these changes

2020-12-15 14:22 UTC, Rinkeeee96 commented
Kijk er vnv nog even naar na werk. Dan kan ik hem pullen.

2020-12-15 19:53 UTC, Rinkeeee96 approved these changes

2020-12-16 11:10 UTC, wieltar approved these changes

2020-12-16 11:48 UTC, TheLarsJansen approved these changes

2020-12-16 12:10 UTC, Rinkeeee96 approved these changes

2020-12-16 12:10 UTC, merged