Feature/coins shop etc
Rinkeeee96/FoxTrot_SA_Engine pull request #168
Opened 2020-12-20 20:16 UTC by Rinkeeee96

2020-12-22 08:14 UTC, ttleeuw reviewed
Als tutorial erin zit misschien hier ook even met coins werken -> laat de speler in contact komen met coins en inventory scherm

2020-12-22 21:23 UTC, Rinkeeee96 commented
TODO:
Wanneer een enemy je kilt krijg je 100 coins. Dat is even voor nu om de shop te kunnen testen.

2020-12-23 08:24 UTC, Rinkeeee96 commented
TODO
Maximaal aantal hartjes cappen. Eventueel maken dat player altijd 2 hartjes heeft. Wanneer hij meer koopt en verliest dan blijven ze weg.

2020-12-23 08:27 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Shop/Shop.h
> +	function<void(void)> doSomethingYouStupidCunt = [this]() {
Deze naam moet ik nog even aanpassen. De knop wou niet helemaal werken gister en was gefrustreerd.

2020-12-23 08:39 UTC, ttleeuw commented
Ziet er netjes uit en werkt ook goed! Heb bij TODO comments commentaar gezet.

Klein dingetjes;
- Shop beter uitlijnen/netter maken van de teksts

2020-12-23 09:08 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/BaseEnemy.cpp
> +		this->player->inventory.coins = 100;
+= van maken dan telt ie al op volgens mij

2020-12-23 09:08 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.cpp
> +	cout << "start" << endl;
Cout op develop alleen met debug flag of niet

2020-12-23 09:08 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Shop/Shop.h
> +#define HEALTH_PRICE 50
Willen we de prijzen hard coded of uit een config json halen?
Een config json is wel veel netter maar wel wat meer tijd

2020-12-23 09:08 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Shop/Shop.h
> +	function<void(void)> doSomethingYouStupidCunt = [this]() {
Tis ook allemaal lastig soms he 😆

2020-12-23 15:43 UTC, wieltar commented on Glitch/Game/Scenes/Shop/Shop.h
> +#define HEALTH_PRICE 50
ik zou het gewoon zo laten tbh

2020-12-23 15:44 UTC, wieltar commented on Glitch/Game/Scenes/Shop/Shop.h
> +#define HEALTH_PRICE 50
@Rinkeeee96  ik zou dit wel in de general defines zetten, dan word dat het "config file"

2020-12-23 15:45 UTC, wieltar requested changes
zou je even kunnen kijken naar de general defines, zou een mooi config bestandje kunnen worden

2020-12-23 15:46 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Shop/Shop.h
> +#define HEALTH_PRICE 50
Config bestand is nice to have. Eventueel iets voor volgende week. Als het voor nu werkt ben ik van mening prima
@wieltar

2020-12-23 15:47 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Shop/Shop.h
> +#define HEALTH_PRICE 50
In general defines is wel een goeie. Dat ga ik sws even doen

2020-12-24 09:33 UTC, wieltar approved these changes

2020-12-24 09:51 UTC, TheLarsJansen submitted a review, later dismissed

2020-12-24 10:05 UTC, WilliamRossAvans approved these changes

2020-12-24 10:05 UTC, merged