Help screen
Rinkeeee96/FoxTrot_SA_Engine pull request #173
Opened 2020-12-21 13:23 UTC by TheLarsJansen

2020-12-21 13:38 UTC, ttleeuw commented on Glitch/Game/PopUps/IPopup.h
> +#include "Engine\Events\Action\TogglePause.h"
/

2020-12-21 14:17 UTC, wieltar submitted a review, later dismissed

2020-12-21 14:18 UTC, wieltar submitted a review, later dismissed

2020-12-21 15:40 UTC, WilliamRossAvans requested changes
de tekst is er groot, ik zou het qua grote denken aan de grote van het blok rechts boven
moveleft /right veranderen naar moving left/ moving right
Een ander leuk idee? --> knop om de popup af te sluiten?

2020-12-21 15:40 UTC, WilliamRossAvans commented on Glitch/Assets/Savegame/saveGameData.json
> +{"savegames":[{"achievements":["Level 1 completed!","Level 2 completed!","Level 3 completed!"],"leveldata":[{"completed":false,"levelnr":0,"score":100},{"completed":true,"levelnr":1,"score":100},{"co
niet naar develop

2020-12-21 20:20 UTC, Rinkeeee96 reviewed
Ziet er KISS uit. Zou idd alleen de tekst even goed resizen dat het er netjes uitziet.

2020-12-22 08:10 UTC, ttleeuw commented on Glitch/Assets/Savegame/saveGameData.json
> +{"savegames":[{"achievements":["Level 1 completed!","Level 2 completed!","Level 3 completed!"],"leveldata":[{"completed":false,"levelnr":0,"score":100},{"completed":true,"levelnr":1,"score":100},{"co
Een ander leuk idee? --> knop om de popup af te sluiten?.

Zou dat niet doen, vaak is het dat je een popup afsluit door nogmaals op de knop de drukken, denk niet dat het veel van toegevoegde waarde is

2020-12-22 08:11 UTC, ttleeuw commented on Glitch/Game/PopUps/HelpMenu/HelpMenu.h
> +	unordered_map<KeyCode, string> keycodeStringMap = {
Is dit alleen voor het hulp menu van belang? Misschien iets voor in de engine

2020-12-22 08:13 UTC, ttleeuw reviewed
Ziet er netjes uit, comment van @WilliamRossAvans zo na standup misschien even overhebben. Misschien ook even op mijn comment terugkomen

2020-12-22 14:03 UTC, WilliamRossAvans approved these changes

2020-12-22 19:10 UTC, Rinkeeee96 approved these changes

2020-12-22 19:12 UTC, merged