Fps new
Rinkeeee96/FoxTrot_SA_Engine pull request #18
Opened 2020-10-14 16:35 UTC by Maxvani

2020-10-14 17:10 UTC, Rinkeeee96 commented on Glitch/src/Glitch/Core/Application.h
> +#include <Glitch\FPS\FrameData.h>
Includes binnen je eigen project horen via "" te gaan. 
Zie dat dit in het gehele glitch project niet klopt.

2020-10-14 17:16 UTC, Rinkeeee96 commented on Glitch/src/Glitch/Renderer/Renderer2d.h
> +		bool shouldDrawFps;
Nooit leeg initializeren

2020-10-14 17:17 UTC, Rinkeeee96 commented on Glitch/src/Glitch/FPS/FrameData.h
> +using namespace std;
Dit staat al in de precompiled headers? Daar gebruik van maken

2020-10-14 17:17 UTC, Rinkeeee96 commented on Glitch/src/Glitch/FPS/FrameData.cpp
> +using namespace std;
Dit zet je niet in de .cpp file neer

2020-10-14 17:17 UTC, Rinkeeee96 commented on Glitch/src/Glitch/FPS/FrameData.cpp
> +#include "glpch.h"
Hoort in de .h file

2020-10-14 17:18 UTC, Rinkeeee96 commented on Glitch/src/Glitch/FPS/FrameData.cpp
> +double FrameData::loopFps = 0;
Mag je niet definen in de .cpp file

2020-10-14 17:21 UTC, Rinkeeee96 commented on Glitch/src/Glitch/Facades/SDL2/SDL2Facade.cpp
> +	void SDL2Facade::drawMessageAt(const Message& message, const Position& pos)
Met het gebruiken van references impliceer je dat deze geweizigd worden. Message wordt aan het einde van deze functie weggegooid? Pos wordt niks mee gedaan. Pos hoeft geen reference te zijn. Message ook niet. Je bent hier data aan het verwijderen die jij niet beheert?

2020-10-14 17:21 UTC, Rinkeeee96 commented on Glitch/src/Glitch/Facades/SDL2/SDL2Facade.h
> +#include <filesystem>
Consistent gebruik van ""

2020-10-14 17:23 UTC, Rinkeeee96 commented on Glitch/src/Glitch/Core/Application.cpp
> +			frameData->startTimer();
Er wordt nog niet dynamisch fps geregeld? Als ik hem nu run draait hij op 1300 fps. Kan dit al gelockt worden naar 60?

2020-10-14 17:23 UTC, Rinkeeee96 commented on Glitch/src/Glitch/Core/Application.cpp
> +		frameData = new FrameData;
is Framedata een singleton? Als Glitch 1 instance van framedata bezit hoeft dit geen pointer te zijn.

2020-10-14 17:25 UTC, Rinkeeee96 commented on Glitch/src/Glitch/Core/Application.cpp
> +	bool Application::OnKeyPressed(KeyPressedEvent& e) {
Dit is een bool maar returnt altijd true? Maak hier of een void van of return false bij een error

2020-10-14 17:27 UTC, Rinkeeee96 commented on Glitch/src/Glitch/FPS/FrameData.h
> +	static double loopFps;
Getters en setters?

2020-10-15 05:54 UTC, ttleeuw commented on Glitch/src/Glitch/FPS/FrameData.cpp
> +#include "glpch.h"
glpch.h (enige include) die in de cpp file moet omdat het een lib is

2020-10-15 06:13 UTC, ttleeuw requested changes

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Core/Application.cpp
> +			FrameData::loopFps = frameData->calculateAverageFps();
Zet alles in de namespace Glitch, zorgt ervoor dat dit niet hoeft

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Core/Application.cpp
> +			frameData->startTimer();
Ditto, kijk naar hoelang de Run duurt binnen de Run van application en doe aan de hand hiervan een sleep

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Core/Application.cpp
> +	bool Application::OnKeyPressed(KeyPressedEvent& e) {
Ditto, return true in if statement anders false

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Core/Application.h
> +		FrameData* frameData;
Maak dit geen pointer

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/FPS/FrameData.cpp
> +double FrameData::renderFps = 0;
zet #define in de .h, voor voorbeeld kijk naar PhysicsFacade

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/FPS/FrameData.h
> +#include <iostream>
Ook iostream staat in de precompiled header (gpch.h)

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/FPS/FrameData.h
> +#include <SDL.h>
Ik zie een SDL include, wanneer we van window/renderer wisselen moet zowel in de facade als in deze klassen iets aangepast gaan worden. Maak gebruik van de facade

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Facades/SDL2/SDL2Facade.cpp
> +		Sans = TTF_OpenFont("../Assets/Fonts/Sans.ttf", 24);
Aparte methode voor inladen van font, zodat men van font kan wisselen?

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Facades/SDL2/SDL2Facade.cpp
> +		bool exists = std::filesystem::exists("../Assets/Fonts/Sans.ttf"); // TODO dynamic fonts
Maak hier een variabelen van zodat dit niet specifiek voor deze font is, en gewijzigd kan worden

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Facades/SDL2/SDL2Facade.cpp
> +			Message_rect.w = 150;
geef message deze variabelen ook mee, dan kan de methode beter hergebruikt worden

2020-10-15 06:13 UTC, ttleeuw commented on Glitch/src/Glitch/Renderer/Renderer2d.cpp
> +		frameData->startTimer();
Moet dit in de renderer of in de application?

2020-10-15 16:46 UTC, closed without merging