New overworld
Rinkeeee96/FoxTrot_SA_Engine pull request #197
Opened 2020-12-28 22:09 UTC by Maxvani

2020-12-28 23:08 UTC, wieltar requested changes
De text van het sneeuw level is erg moeilijk te lezen vanwege de bergen die erachter zitten, zou je die kunnen verplaatsen?

2020-12-29 09:49 UTC, ttleeuw commented
Weet niet wat de rest ervan denk maar;
Ik vind de overworld een beetje aan de kleine kant vergeleken met de vorige (heel veel blauw)

2020-12-29 10:31 UTC, TheLarsJansen commented
Ben het met Thijs eens dat het een beetje veel blauw is maar vind het niet perse lelijk of slecht. Vind hem wel prima zo.

Onder level 2 zit wel een raar dingetje, zie foto:
![image](https://user-images.githubusercontent.com/43005884/103277422-3ae0d780-49c9-11eb-9240-b29975d461c2.png)

2020-12-29 12:48 UTC, wieltar approved these changes

2020-12-29 12:51 UTC, TheLarsJansen approved these changes
Tis heel mieren neukerig maar vind dat boompje achter de text beetje raar.
Weet niet hoeveel werk het is om het weg te halen als het niet zoveel werk is dan ff doen en anders laat maar staan
![image](https://user-images.githubusercontent.com/43005884/103284913-e0517680-49dc-11eb-8684-fda4055a47cd.png)

2020-12-29 12:59 UTC, Rinkeeee96 approved these changes

2020-12-29 12:59 UTC, TheLarsJansen approved these changes

2020-12-29 13:02 UTC, wieltar approved these changes

2020-12-29 13:02 UTC, merged