[WIP] Scene layers
Rinkeeee96/FoxTrot_SA_Engine pull request #21
Opened 2020-10-15 16:55 UTC by Rinkeeee96

2020-10-18 20:27 UTC, Rinkeeee96 commented
Moet alleen nog even doxygen toevoegen.

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.cpp
> +void Engine::insertScene(Scene* scene)
const

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.h
> +	void insertScene(Scene * scene);
const

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +		if (layer->layerIdentifier == layer1)
Reden dat het een string is en geen int?

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::switchLayers(const string layer1, const string layer2)
altijd maar twee layers, vector meegeven?

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	Layer * layer = new Layer;
layer meegeven? Ipv identifier laat een andere classen verantwoordelijk zijn voor het creeeren

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	if (layerIdentifier == "") return false;
throw error

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +	createLayer(layerIdentifier,false);
Heeft een scene meerdere layers of heeft een layer meerdere scenes?
Bij een scene meerdere layers, geeft hier de layer mee en laat de "Game" verantwoordelijk voor het maken van de layer

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	void createLayer(const string layerIdentifier, const bool render);
Geef verantwoordelijkheid creeeren van layer aan de "Game"

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	vector <Object*> getAllObjectsInScene();
Moet je de objecten per layer weten? Of het dit een verandwoordelijkheid van Scene qua volgorde objecten returnen

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	//vector<Object*> getObjectInLayer();
remove

2020-10-19 09:37 UTC, ttleeuw commented on engineFoxtrot/Main/main.cpp
> +	testScene->addNewObjectToLayer("MiddleLayer", object2);
Geen layer class een z-Index voor het tekenen

2020-10-19 10:04 UTC, WilliamRossAvans requested changes
Het zou ook nog mooi zijn als er 2 layers achter elkaar worden getekend.

2020-10-19 10:04 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/SceneManager/SceneManager.cpp
> +	if (scene == nullptr) return;
throw error?

2020-10-19 10:15 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::createLayer(const string layerIdentifier, const bool render)
![image](https://user-images.githubusercontent.com/10192977/96432169-c9d0b700-1204-11eb-87dd-3ee0689e6e55.png)

2020-10-19 10:15 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +const bool Scene::toggleLayer(const string layerIdentifier)
![image](https://user-images.githubusercontent.com/10192977/96432173-cdfcd480-1204-11eb-9dc4-f0be01ac9e9c.png)

2020-10-19 10:16 UTC, Rinkeeee96 commented on engineFoxtrot/Main/main.cpp
> +	testScene->addNewObjectToLayer("MiddleLayer", object2);
geen of geef?

2020-10-19 10:55 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::switchLayers(const string layer1, const string layer2)
![image](https://user-images.githubusercontent.com/10192977/96441765-56ca3f00-120a-11eb-8f10-7bf02c67a743.png)

2020-10-19 12:05 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/SceneManager.cpp
> +	cout << "Setting current scene to " << sceneID << " with amount of obj: " << currentScene->getAllObjectsInScene().size() << endl;
Weer zo een cout, of onder een DEBUG macro hangen.

2020-10-19 12:05 UTC, TheLarsJansen commented on engineFoxtrot/LayerSelection.h
> +	LAYER_SELECTION__7			= 0x08
Limiteert dit tot 8 layers?

2020-10-19 12:47 UTC, ttleeuw commented on engineFoxtrot/Main/main.cpp
> +	testScene->addNewObjectToLayer("MiddleLayer", object2);
Geef

2020-10-19 13:11 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::switchLayers(const string layer1, const string layer2)
Ik snap het idee dan niet van layers omwisselen, in welk geval zou dit gebeuren?

2020-10-20 08:04 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Engine.cpp
> +void Engine::insertScene(Scene* scene)
const bij pointer gaat niet

2020-10-20 08:04 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Engine.h
> +	void insertScene(Scene * scene);
const bij pointer gaat niet

2020-10-20 08:05 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::switchLayers(const string layer1, const string layer2)
Stel je wil het ene moment het ene voor t ander tekenen en het andere moment wisselen. Heb de mogelijkheid beschikbaar gemaakt of het gebruikt gaat worden gaan idee.

2020-10-20 08:06 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	vector <Object*> getAllObjectsInScene();
Als je kijkt wat deze functie gebruikt is dat Video en Physics. De scene zelf is afhankelijk van 1 vector returnen van alle objecten. Zodat Video niks van layers zal afweten. Doordat Video van voor naar achter door die vector loopt kan Scene zelf de layers achter elkaar plakken.

2020-10-20 08:11 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::switchLayers(const string layer1, const string layer2)
Dan zou ik zeggen dat het op dat moment pas geimplementeerd hoeft te worden, nu zorgt het voor extra code die niet gebruikt wordt

2020-10-20 08:19 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +		if (layer->layerIdentifier == layer1)
Goeie, z-index lijkt me idd beter om mee te werken. ff ombouwen

2020-10-20 08:22 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Layer.h
> +#include "../stdafx.h"
Omdat ik hem include in een .h bestand pakt hij hem anders niet.

2020-10-20 08:43 UTC, wieltar requested changes

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +	if (currentSceneID != (*pointerToCurrentScene)->getSceneID())
Waarom wordt hier eigenlijk je sceneID gebruikt in plaats van een pointer naar je scene?

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +	if (currentSceneID != (*pointerToCurrentScene)->getSceneID())
het lijkt me dat alles toch mee veranderd met scenes dus dan zou dit makklijker zijn dan een lijst van objecten bijhouden en de hele tijd een scene id zetten samen met het veranderen van de lijst van objecten. Het lijkt me dat alles toch mee veranderd met een scene.

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	Scene** pointerToCurrentScene = nullptr;
oke dus je slaat hem wel op, en trekt je objecten hieruit, had ik hierboven nog niet in de gaten maar ik snap niet helemaal wat de check op dat scene id dan doet aangezien je toch altijd met je scene meeveranderd

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	int currentSceneID = 0;
kunnen objecten dan tussen scenes verplaatsen?

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SVI(Temp)/SVIEngine.cpp
> +		if ((*pointerToCurrentScene)->getAllObjectsInScene().size() <= 0) return;
als size 0 is dan loopt je for loop toch niet? lijkt me een beetje overbodig met al die if statements aangezien je al kijkt of je scene bestaat

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SVI(Temp)/SVIEngine.cpp
>  			if (obj != nullptr) {
kan een scene nulllptr objects bevatten? dit zou niet moeten kunnen toch?
Als je in scene een nullptr obj insert dan moet die toch al zeggen van HE...MAG NIET JONGE

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Layer.h
> +	string layerIdentifier;
kunnen we niet zonder als we de layers wat meer verantwoordelijkheden geven over zichzelf?

een loop in de scenemanager over de layers die dan de onupdate aanroept, zodat hij zichzelf kan tekenen etc.?

dan omzeil je ook het gekke ding dat je video een layer kan tekenen in een totaal andere volgorde dan in je scenemanger is bedoeld.

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
>  bool Scene::checkIfObjectExists(const int objectID)
is deze niet overbodig als we al met object references werken als we een scene gebruiken?

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
>  bool Scene::checkIfObjectExists(const int objectID)
dan bestaat een object toch altijd aangezien we deze zelf toevoegen aan de scene en aanroepen met de reference?

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +		if (layer->layerIdentifier == layer1)
kan je dan niet werken met een stack? die forceert altijd een volgorde af op basis van insertion, dan zou je met de boolean kunnen afdwingen of hij getekend moet worden en hoef je geen z-index bij te houden.

Wat gebeurt er namelijk als je 2 layers hebt met dezelfde z-index?

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +const bool Scene::toggleLayer(const string layerIdentifier)
dit misschien neerleggen bij de implementatie van een layer? bijvoorbeeld bij een pause menu dat er op een bepaalde keypress (esc?) of knop in menu binnen een render functie de boolean kan worden geflipt? of is dat niet wenselijk?

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +const bool Scene::addNewObjectToLayer(const string layerIdentifier, Object* object)
zou je hiervoor niet een functie kunnen maken in de layer zelf? dus ipv een struct een class met meer verantwoordelijkheden? een beetje wat ik hierboven een keer eerder aangaf

2020-10-20 08:43 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	vector <Object*> getAllObjectsInScene();
nu krijg je het probleem dat je de volgorde van het tekenen van je layers niet  kan afdwingen in je video en dat je dus geen garantie meer hebt van wat nu getekend wordt, kan je dit niet binnen de scenemanger houden om die volgorde af te dwingen?

2020-10-21 18:24 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsEngine.cpp
> +	if (currentSceneID != (*pointerToCurrentScene)->getSceneID())
Omdat box2d elke keer opnieuw geinit moet worden met de nieuwe objecten. Video werkt wel zo, maar box2d kan niet anders.

2020-10-21 18:24 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	int currentSceneID = 0;
Zie vorige comment

2020-10-21 18:25 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsEngine.h
> +	Scene** pointerToCurrentScene = nullptr;
Zie vorige comment

2020-10-21 18:26 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +const bool Scene::toggleLayer(const string layerIdentifier)
Opgelost door een bool mee te laten geven. Meer controlle aan game

2020-10-21 18:26 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +const bool Scene::addNewObjectToLayer(const string layerIdentifier, Object* object)
Layer implementatie hou ik liever binnen de Scene. Aangezien een layer niet zo complex is. Het is alleen een z index, thats it.

2020-10-21 18:27 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
>  bool Scene::checkIfObjectExists(const int objectID)
Mocht de game willen checken of een object id bestaat. Is hier de mogelijkheid voor.

2020-10-23 13:27 UTC, ttleeuw commented
Pull develop hier nogmaals in. Zie dat er verschillende conflicten zijn in oude branches. 

Scenemanager ziet er goed uit maar ik zie een probleem met het wisselen van scenes, waar leggen we de verantwoordelijkheid van het wisselen hiervan? Momenteel is de SceneManager hiervoor verantwoordelijk.

Op deze manier moet een scene de scenemanager kennen;
LevelOne : Scene {
   public void OnComplete() {
       SceneManager.SetScene(Level2);
   }
}

En moeten alle scenes van te voren ingeladen worden? Op hoe gaat dit opgelost worden?

2020-10-23 13:32 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsFacade.cpp
> +	bodyDef.angularVelocity = object->getSpeed();
Was dit niet een bug die nog opgelost moet worden? Is dit hiermee opgelost? Zo nee dan zou dit weghalen

2020-10-23 13:32 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::switchLayers(const int zIndex, const int zIndex2)
Deze zou niet gebruikt gaan worden toch?

2020-10-23 13:32 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/SceneManager.h
>  	void createNewScene(const int sceneID);
InsertScene, is deze dan nog wel nodig?

2020-10-23 13:36 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +void Scene::switchLayers(const int zIndex, const int zIndex2)
Dan haal ik hem weg. Ging over een andere functie toen. Maar zal m weghalen

2020-10-23 13:36 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsFacade.cpp
> +	bodyDef.angularVelocity = object->getSpeed();
Ja dit was een bug, hier zou jij naar kijken?

2020-10-23 13:37 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SceneManager.h
>  	void createNewScene(const int sceneID);
Goeie, haal ik ook weg

2020-10-23 13:45 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsFacade.cpp
> +	bodyDef.angularVelocity = object->getSpeed();
Ja klopt ik zal het zo snel mogelijk oppakken. Maar zou deze regel uitcommenten en een TODO bijzetten. ( weet of dit iets sloopt in de brache bewegen met input omdat daar ook met speed wordt gewerkt )

2020-10-26 15:00 UTC, Rinkeeee96 commented
> Pull develop hier nogmaals in. Zie dat er verschillende conflicten zijn in oude branches.
> 
> Scenemanager ziet er goed uit maar ik zie een probleem met het wisselen van scenes, waar leggen we de verantwoordelijkheid van het wisselen hiervan? Momenteel is de SceneManager hiervoor verantwoordelijk.
> 
> Op deze manier moet een scene de scenemanager kennen;
> LevelOne : Scene {
> public void OnComplete() {
> SceneManager.SetScene(Level2);
> }
> }
> 
> En moeten alle scenes van te voren ingeladen worden? Op hoe gaat dit opgelost worden?

Verantwoordelijkheid zal bij de game liggen. Ik wil niet de scene zelf verantwoordelijk maken voor het bewegen naar de volgende Scene. Aangezien een scene niet zal weten wat hij of zij is.

2020-10-26 15:25 UTC, wieltar commented
> 
> 
> > Pull develop hier nogmaals in. Zie dat er verschillende conflicten zijn in oude branches.
> > Scenemanager ziet er goed uit maar ik zie een probleem met het wisselen van scenes, waar leggen we de verantwoordelijkheid van het wisselen hiervan? Momenteel is de SceneManager hiervoor verantwoordelijk.
> > Op deze manier moet een scene de scenemanager kennen;
> > LevelOne : Scene {
> > public void OnComplete() {
> > SceneManager.SetScene(Level2);
> > }
> > }
> > En moeten alle scenes van te voren ingeladen worden? Op hoe gaat dit opgelost worden?
> 
> Verantwoordelijkheid zal bij de game liggen. Ik wil niet de scene zelf verantwoordelijk maken voor het bewegen naar de volgende Scene. Aangezien een scene niet zal weten wat hij of zij is.

Is het dan zo dat elke scene een onComplete etc. krijgt (verschillende state handlers) die bij de game moeten worden geimplementeerd? Heb je daar toevallig al een idee bij?

2020-10-26 15:54 UTC, Rinkeeee96 commented
> > > Pull develop hier nogmaals in. Zie dat er verschillende conflicten zijn in oude branches.
> > > Scenemanager ziet er goed uit maar ik zie een probleem met het wisselen van scenes, waar leggen we de verantwoordelijkheid van het wisselen hiervan? Momenteel is de SceneManager hiervoor verantwoordelijk.
> > > Op deze manier moet een scene de scenemanager kennen;
> > > LevelOne : Scene {
> > > public void OnComplete() {
> > > SceneManager.SetScene(Level2);
> > > }
> > > }
> > > En moeten alle scenes van te voren ingeladen worden? Op hoe gaat dit opgelost worden?
> > 
> > 
> > Verantwoordelijkheid zal bij de game liggen. Ik wil niet de scene zelf verantwoordelijk maken voor het bewegen naar de volgende Scene. Aangezien een scene niet zal weten wat hij of zij is.
> 
> Is het dan zo dat elke scene een onComplete etc. krijgt (verschillende state handlers) die bij de game moeten worden geimplementeerd? Heb je daar toevallig al een idee bij?

Nee een scene zal geen onComplete krijgen. De game is verantwoordelijk om te checken of een level behaald is en hoe dat afgehandelt wordt. Aangezien input ook niet naar de scenemanager gaat kan de scene niet checken of er bijvoorbeeld op een knop gedrukt is oid. Dat is mijn gedachte dan

2020-10-26 18:23 UTC, ttleeuw approved these changes
Netjes

2020-10-26 18:43 UTC, TheLarsJansen approved these changes
Ik vind helemaal mooi

2020-10-27 12:41 UTC, WilliamRossAvans approved these changes

2020-10-27 16:35 UTC, wieltar approved these changes

2020-10-27 16:36 UTC, wieltar commented
> 
> 
> > > > Pull develop hier nogmaals in. Zie dat er verschillende conflicten zijn in oude branches.
> > > > Scenemanager ziet er goed uit maar ik zie een probleem met het wisselen van scenes, waar leggen we de verantwoordelijkheid van het wisselen hiervan? Momenteel is de SceneManager hiervoor verantwoordelijk.
> > > > Op deze manier moet een scene de scenemanager kennen;
> > > > LevelOne : Scene {
> > > > public void OnComplete() {
> > > > SceneManager.SetScene(Level2);
> > > > }
> > > > }
> > > > En moeten alle scenes van te voren ingeladen worden? Op hoe gaat dit opgelost worden?
> > > 
> > > 
> > > Verantwoordelijkheid zal bij de game liggen. Ik wil niet de scene zelf verantwoordelijk maken voor het bewegen naar de volgende Scene. Aangezien een scene niet zal weten wat hij of zij is.
> > 
> > 
> > Is het dan zo dat elke scene een onComplete etc. krijgt (verschillende state handlers) die bij de game moeten worden geimplementeerd? Heb je daar toevallig al een idee bij?
> 
> Nee een scene zal geen onComplete krijgen. De game is verantwoordelijk om te checken of een level behaald is en hoe dat afgehandelt wordt. Aangezien input ook niet naar de scenemanager gaat kan de scene niet checken of er bijvoorbeeld op een knop gedrukt is oid. Dat is mijn gedachte dan

Dat is dan ook niet de verantwoordelijkheid van de scene base class maar van de concrete implementatie, maar daar komen we tegen die tijd wel, goedgekeurd

2020-10-27 16:36 UTC, merged