[WIP] Animation new
Rinkeeee96/FoxTrot_SA_Engine pull request #24
Opened 2020-10-19 09:22 UTC by WilliamRossAvans

Load animations + sprites
Run animations
Cleanup object
Removing unsused sprites + edit charecter sprite

2020-10-19 09:42 UTC, ttleeuw commented
Merge develop in branche

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Engine.cpp
> +	sviEngine.loadSprite(spriteID, filename, singleSpriteHeight, singleSpriteWidth, size);
Waarom is de error throwing uit gecomment?

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Events/EventManager.cpp
> +#include "stdafx.h";
1 is genoeg lijkt mij. Zonder ../ moet je gebruiken

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SVI(Temp)/SVI.h
> -	void renderCopy(const int spriteID, const int xPos, const int yPos, const int width, const int height, const int rotation);
Moeten we deze niet houden als overloaded functie voor als je een sprite wil showen die niet in de object list staat?

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SVI(Temp)/SVIEngine.cpp
doxygen

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	int getSpriteID();
Moet const zijn

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.h
> -	void addNewObject(const int id, const int xPos, const int yPos, const int height, const int width, const int speed, const int jumpHeight, const int density, const int friction, const int restitution
Ik ga er vanuit dat alles wat je weg haalt ook echt weg kan en niet meer nodig is.

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/SpriteObject.cpp
> +using namespace std;
Staat als het goed is al in de PCH dus hoeft hier niet meer

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/SpriteObject.cpp
> +#include "stdafx.h"
Zelfde als bij andere comment. Die zonder ../ is genoeg

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	SpriteObject(const int _textureID, const int _size, const int _height, const int _width) : textureID(_textureID), lengthOfTextures(_size), height(_height), width(_width) {}
Tis overzichtelijker als je dit even uitschrijft in de .cpp.

2020-10-19 15:51 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	SpriteObject(const int _textureID, const int _size, const int _height, const int _width) : textureID(_textureID), lengthOfTextures(_size), height(_height), width(_width) {}
Of onder elkaar

2020-10-20 07:55 UTC, ttleeuw commented on engineFoxtrot/Main/main.cpp
> +	object->registerSprite("default", 100);
String is niet zo netjes, kan op vershillende manieren fout gaan

2020-10-20 07:55 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	void registerSprite(std::string state, int spriteID);
String is niet zo netjes, kan op vershillende manieren fout gaan

2020-10-20 07:55 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	std::map<std::string, int> textures = std::map<std::string, int>();
Sprite class als map? Zodat het object verantwoordelijk is voor zetten van texture?

2020-10-20 08:02 UTC, wieltar commented
Ik had verwacht dat Object een referentie zou hebben naar TextureObject en dat hier textures in zitten ongeacht of het een animatie is en dat dit resolved is zodra hij is ingeladen ofzo

 Niet dat dit pas wordt geresolved in te facade, nu is het mogelijk om hier een animatie te missen afhankelijk van je facade lijkt me?

![afbeelding](https://user-images.githubusercontent.com/22468530/96557174-2f32af80-12ba-11eb-8fc4-98ac3180f942.png)

Also, wat is de deal met de animated texture map en de normale texturemap? die animated wordt hier niet echt gebruikt? Het is heel onduidelijk. Ik zie nu dat dit elk frame wordt gedaan  maar waarom stuur je hier dan geen sprite object mee ipv al die parameters?

2020-10-20 08:06 UTC, ttleeuw commented
clickup:
Als een Speler
Wil ik Minstens één speelbaar karakter met minstens 2 acties
Zodat ik Me kan identificeren met het figuur én problemen op verschillende manieren op kan lossen.

Beschrijving klopt niet echt bij de US

2020-10-20 08:14 UTC, wieltar requested changes

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/Engine.cpp
> +#include <filesystem>
kan dit niet in de precompiled header?

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/Engine.h
> +	void loadSprite(int spriteID, const char* filename, int singleSpriteHeight, int singleSpriteWidth, int size);
Kan je hier niet een sprite object forceren ipv al die parameters? is wat netter

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/Events/EventManager.cpp
> +#include "../stdafx.h"
let erop dat je werkt vanaf de root dir  voor constantheid

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/SVI(Temp)/ISVI.h
> +	virtual void loadSprite(int spriteID, const char* filename, int singleSpriteHeight, int singleSpriteWidth, int size) = 0;
/|\
 |

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/SVI(Temp)/SVI.h
> -	void renderCopy(const int spriteID, const int xPos, const int yPos, const int width, const int height, const int rotation);
Ik zou dat dan gewoon doen met een geforceerd sprite obj ipv losse parameters

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/SVI(Temp)/SVI.h
> +	void loadSprite(int spriteID, const char* filename, int singleSpriteHeight, int singleSpriteWidth, int size);
sprite obj

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/SVI(Temp)/SVI.h
> +	unordered_map<int, SpriteObject*> animatedTextureMap;
kunnen deze 2 niet samen worden gevoegd in 1 sprite object zodat er daar kan worden beslist of iets geanimeerd wordt ipv in de facade? lijkt me ook wat onderhoudbaarder

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/SVI(Temp)/SVI_Video.cpp
> +	Uint32 pos = seconds % sprite->getAmountOfTextures();
Wat gebeurd er nu als ik "ren" met mijn sprite? is het dan dat de animatie mee gaat met de rensnelheid of blijft deze gelijk en krijg je een soort van floating/schuif effect

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Object.cpp
> +int Object::getSpriteID() { return spriteID; }
let op const correctness

2020-10-20 08:14 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Object.cpp
> +void Object::registerSprite(const std::string state, const int spriteID) {
state evt anders afhandelen ? in een state object en dat het bijvoorbeeld mogelijk is om een aantal standaard states in de engine te plaatsen en dan dit over te erven in de game zodat de game meer states kan toevoegen?

een soort uitgebreide enum?

2020-10-20 16:06 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/SVI(Temp)/SVI_Video.cpp
> +	Uint32 pos = seconds % sprite->getAmountOfTextures();
Je krijgt een animatie die rent

2020-10-21 18:29 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Object.cpp
> +Object::Object()
Dit laten staan idd

2020-10-21 18:32 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Events/EventManager.cpp
> +#include "stdafx.h";
Waarom staat hier een ;?

2020-10-21 18:33 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/General/ErrorCodes.h
> +#define ERROR_CODE_IMAGE_FILE_NOT_FOUND								0x12
Ook toevoegen aan de const char array hieronder, anders kan hij niet geprint worden

2020-10-21 18:33 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsFacade.cpp
> +	cout << "Pushing back obj: spriteid: " << object->getObjectId() << endl;
Of cout verwijderen of een debug van maken

2020-10-21 18:35 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Object.h
> +#include <string>
We hebben precompiled headers voor een rede?

2020-10-21 18:36 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int getTextureID() const;
const

2020-10-21 18:37 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int getAmountOfTextures() const;
const

2020-10-21 18:37 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int getWidth() const;
Hier nog 2x

2020-10-21 18:37 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int width;
Init ze op 4, wel zo netjes

2020-10-21 18:37 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int width;
Init deze 4 op 0*

2020-10-21 18:38 UTC, Rinkeeee96 commented on engineFoxtrot/Main/main.cpp
> +	SpriteObject so0(1, 16, 16, 1);
Let goed op of je dit een pointer wil maken of hoe. Het is nu geen pointer dus wanneer je uit deze scope bent zal het verdwijnen.

2020-10-21 18:39 UTC, Rinkeeee96 commented on engineFoxtrot/Main/main.cpp
> +	engine.startTickThreads();
Laat dit in de setup staan

2020-10-21 18:39 UTC, Rinkeeee96 commented on engineFoxtrot/Main/main.cpp
> +		for (int i = 0; i < 100; i++)
Waarom een for loop als je ook gwn de game kan laten lopen? Laat het gwn staan zoals het is.

2020-10-23 13:36 UTC, ttleeuw commented
Pull develop nogmaals in branche, verschillende conflicten

2020-10-29 13:56 UTC, ttleeuw commented
Ik zie dat het veranderen van state er niet inzit, bij stilstaan, veranderen van richting etc

2020-10-29 18:49 UTC, Rinkeeee96 commented
@WilliamRossAvans Zou je al die assets in een andere pr kunnen zetten? Pr is heel onoverzichtelijk

2020-10-29 18:58 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +
Doxygen voor de gehele klasse?

2020-10-29 18:58 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int textureID;
const?

2020-10-29 18:59 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int height = 0;
Heb je de getters en setters const gemaakt maar is handig als je de var ook const maakt

2020-10-29 18:59 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Sound/SoundFacade.h
> +#include <SDL.h>
Graag sdl niet includen in .h files. Dit lekt door. Vorige week al aangegeven

2020-10-29 18:59 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> -///// @brief
Uitcommenten of verwijderen?

2020-10-29 19:00 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Sound/SoundFacade.h
> +#include <SDL.h>
Zie dat ik dit al gefixt heb op develop? Verkeerde merge? Even goed checken.

2020-10-29 19:01 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoFacade.h
> +private:
2x private?

2020-10-29 19:28 UTC, TheLarsJansen requested changes
Volgens mij veel merge fouten zoals Rinke op whatsapp al zei.
Daarnaast functies zomaar aanpassen die ergens anders ook gebruikt worden is niet netjes.

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/General/ErrorCodes.h
Hier klopt dus echt niks meer van...

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsBody.h
>  public:
Geen doxygen boven class. Box2D direct geinclude ook niet de bedoeling.

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsBody.h
>  public:
Ook object onderaan moet geinit worden als nullptr, maar kan daar geen comment zetten

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	std::string name;
Moeten ge init worden

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	std::map<std::string, SpriteObject> textures = std::map<std::string, SpriteObject>();
map<string, SpriteObject> textures; is voldoende. std hoeft niet en her initen is ook niet nodig.
Zie het als een vector waar je zegt vector<string> test = vector<string(); Is bij allebei niet nodig

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	const char * getfileName() const;
Foute camelCasing

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Sound/SoundFacade.h
> +#undef main
Deze moet dan dus ook weg als aanvulling op Rinke

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> -///// @brief
verwijderen als het niet gebruikt wordt/ redundant/ outdated is

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +void VideoEngine::loadImage(const SpriteObject spriteObject)
loadImage aanpassengaat niet zomaar.
Hiermee sloop je een hoop andere dingen.
Hier moet je een overloaded function voor maken

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.h
> +	void loadImage(const SpriteObject spriteObject);
Zie comments in VideoEngine.cpp

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +		throw ERROR_CODE_SDL2FACADE_SPRITE_DOESNT_EXISTS;
Ook hier een overloaded function voor maken.
De rendercopy zomaar vernaderern sloopt een hoop

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +	Uint32 seconds = ticks / 300;
Its a kind of magic

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +	SDL_Rect rect{ leftpos, 0, sprite->getWidth(), sprite->getHeight() };
Hier wordt een Y van 0 meegegeven?
Heeft misschien uitleg nodig en anders,
[Its a kind of magic](https://www.youtube.com/watch?v=PEQBz9LxU_Y )

2020-10-29 19:28 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.h
>  private:
private:
private:
is wel heeeel private, mij iets te private

2020-10-30 20:33 UTC, Rinkeeee96 requested changes
Graag de assets weghalen

2020-11-02 12:47 UTC, wieltar requested changes
Changes van william zijn in orde

Changes van Thijs moeten even aangepast worden voor const correctness in plaats van raw pointers

namespace std weghalen in events

2020-11-02 13:23 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputEngine.cpp
> +	//while (!commandQueue.empty()) {
Dit kan weg als het niet meer nodig is

2020-11-02 13:25 UTC, Maxvani commented on engineFoxtrot/Engine/SceneManager/SpriteObject.h
> +	int getAmountOfTextures() const;
Dit zou dan idd een const int moeten worden ipv een int ... const

2020-11-02 13:28 UTC, Maxvani commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +#define ANIMATIONSPEED 300;
Misschien handig om per animation/spriteset aan te geven wat de animationspeed is? Dan kun je verschillende snelheden hebben voor de animaties

2020-11-02 13:35 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Input/InputEngine.cpp
> +	//while (!commandQueue.empty()) {
Gaat @ttleeuw  fixen

2020-11-02 15:00 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Input/InputEngine.cpp
> +	//while (!commandQueue.empty()) {
@WilliamRossAvans Niet vergeten

2020-11-02 15:02 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Input/InputEngine.cpp
> +	//while (!commandQueue.empty()) {
@Maxvani

2020-11-02 16:18 UTC, ttleeuw approved these changes

2020-11-02 16:26 UTC, Maxvani approved these changes

2020-11-02 16:27 UTC, merged