Fps final
Rinkeeee96/FoxTrot_SA_Engine pull request #29
Opened 2020-10-23 12:18 UTC by Maxvani

Let op! Deze PR bevat niet de koppeling tussen input en het togglen van de fps, alleen de functionaliteit voor het bereken en tekeken van de fps counter en de functie om de fps te togglen

2020-10-23 13:20 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +double FrameData::gameFps = 0;
Deze kun je gwn in de .h op 0 zetten?

2020-10-23 13:20 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	framespersecond = 0;
Kan ook in de .h

2020-10-23 13:21 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Fps/FrameData.h
> +#include <iostream>
Hier heb je precompiled headers voor

2020-10-23 13:21 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Fps/FrameData.h
> +#undef main
Dit hoort hier niet? Dit is sdl2 gerelateerd

2020-10-23 13:22 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Structs/structs.h
> +#pragma once
Als deze structs specifiek voor fps zijn dan rename het naar zoiets

2020-10-23 13:22 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Structs/structs.h
> +	int red, green, blue;
Altijd leeg initten

2020-10-23 13:26 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoEngine.h
> +	FrameData* frameData = nullptr;
private?

2020-10-23 13:27 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +	Sans = TTF_OpenFont("../Assets/Fonts/Sans.ttf", 24);
Moet dit pad hier wel meegegeven worden?

2020-10-23 13:29 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Engine.cpp
> +		FrameData::gameFps = frameData->calculateAverageFps();
Waar is het dyanamisch regelen van de fps? Als ik hem op 60 wil locken?

2020-10-23 13:43 UTC, TheLarsJansen requested changes

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Engine.h
> +	FrameData* frameData;
Initialize op een nullptr

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	//frametimelast = SDL_GetTicks();
Dit moet weg

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return framespersecond;
framespersecong is niet camelCasing.
je returned een float maar framesPerSecond is een double

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	drawFps(FrameData::renderFps, FPS_X, SDL_FPS_Y, "SDL Fps: ");
Deze defines zeggen niet heel veel over de waarde, volgens mij gaat het over position dus is wel mooi om dat ook even in de naam erbij te zetten

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.h
> +	static double renderFps;
Deze moeten private zijn met getters en setters

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +	shouldDrawFps = !shouldDrawFps;
Doxygen

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +	Sans = TTF_OpenFont("../Assets/Fonts/Sans.ttf", 24);
Magic number

2020-10-23 13:43 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +	}
Lege else? Mag weg dan toch?

2020-10-23 15:38 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +double FrameData::gameFps = 0;
Nee dat werkt niet, al geprobeerd. Dan geeft ie aan dat ze const moeten zijn maar dat is niet de bedoeling

2020-10-23 15:39 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.h
> +#include <iostream>
Ah ja die waren er eerst niet en vergeten te verwijderen

2020-10-23 15:40 UTC, Maxvani commented on engineFoxtrot/Engine/Structs/structs.h
> +#pragma once
Het idee was dat deze structs gebruikt kunnen worden door meerdere systemen

2020-10-23 15:44 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.h
> +	static double renderFps;
Ook met een static?

2020-10-23 15:55 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +double FrameData::gameFps = 0;
Dat zou gwn moeten werken..

2020-10-23 15:55 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Structs/structs.h
> +#pragma once
Zou ik ze voor nu wel renamen want het hoort bij de fps.

2020-10-23 16:26 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +double FrameData::gameFps = 0;
Het is wel een static dus volgens mij niet

2020-10-24 10:52 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.h
> +	static double renderFps;
Lijkt me een beetje overbodig dan namelijk

2020-10-25 10:43 UTC, merged