Fps input
Rinkeeee96/FoxTrot_SA_Engine pull request #31
Opened 2020-10-28 10:35 UTC by Maxvani

2020-10-29 16:32 UTC, WilliamRossAvans submitted a review, later dismissed

2020-10-29 16:32 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Input/Commands.h
> +	void execute(InputEngine* inputEngine);
Inputengine in de consturctor zetten, zodat je die niet altijd hoeft mee te geven.

2020-10-29 16:32 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +    inputEngine = _inputEngine;
Dit is niet netjes, Dit is gefixt als je de input engine in de constructor zet van het command.

2020-10-29 16:32 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +                keydown(event);
Altijd een keydown(event) afvuren, dit ivm mogelijke mapping

2020-10-29 16:33 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.h
> +	void toggleFps(Event& fpsEvent); //TODO Toggle via input/Command pattern
nog steeds een todo?

2020-10-29 16:33 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +            if (find(handleOnce.begin(), handleOnce.end(), eventToKeyCode(event)) != handleOnce.end())
misschien vast omschrijven, dat dit niet te afhankelijk wordt van de commands, omdat deze waarschijnlijk toch naar game gaan

2020-10-29 18:44 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +    inputEngine = _inputEngine;
@Maxvani Pak jij dit op dan?

2020-10-30 09:57 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +            if (find(handleOnce.begin(), handleOnce.end(), eventToKeyCode(event)) != handleOnce.end())
Hoeft niet persè, als dit eerder in development komt dat het physics gedeelte kan ik dit oppakken, als er maar een todo en issue van wordt aangemaakt

2020-10-30 11:19 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +    inputEngine = _inputEngine;
👍

2020-10-30 11:28 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +    inputEngine = _inputEngine;
De vraag hier is dan wel hoe dit vanuit de game meegegeven gaat worden

2020-10-30 11:50 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +    inputEngine = _inputEngine;
Heb het nu opgelost door een generic function makeCommand() te maken in engine die via de InputEngine een command maakt en zo zichzelf (de InputEngine) meegeeft aan de command

2020-10-30 11:53 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> +            if (find(handleOnce.begin(), handleOnce.end(), eventToKeyCode(event)) != handleOnce.end())
Ik zal er een issue van maken, want zo te horen heb je er zelf al een idee voor

2020-10-30 20:30 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Input/Commands.cpp
> +Command::Command(InputEngine* _inputEngine) : inputEngine(_inputEngine) {}
Dit is wel extreem lelijk?

2020-10-30 20:31 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Input/InputFacade.cpp
> -    //int SDLInt = (int)(event.key.keysym.scancode);
Uitcommenten of verwijderen?

2020-10-30 20:31 UTC, Rinkeeee96 commented on engineFoxtrot/Main/main.cpp
> +	engine.configureInput(KEY_A, engine.makeCommand<MoveLeft>());
Kunnen we dit overerven in de game?

2020-10-30 20:32 UTC, Rinkeeee96 commented on engineFoxtrot/Main/main.cpp
> +	engine.configureInput(KEY_A, engine.makeCommand<MoveLeft>());
@ttleeuw

2020-11-01 10:29 UTC, ttleeuw requested changes

2020-11-01 10:29 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/InputEngine.h
> +	T* makeCommand() {
Ik denk niet dat de generic goed afgeschermd wordt, voor iedere klassen kan dit aangeroepen worden ook voor een niet command

2020-11-01 10:29 UTC, ttleeuw commented on engineFoxtrot/Main/main.cpp
> +	engine.configureInput(KEY_A, engine.makeCommand<MoveLeft>());
Denk wel dat het een goed idee is, als de generic iets aangepast wordt, en de facade niet meer meegegeven hoeft te worden.

2020-11-01 21:55 UTC, Maxvani commented on engineFoxtrot/Engine/Input/Commands.cpp
> +Command::Command(InputEngine* _inputEngine) : inputEngine(_inputEngine) {}
??? Je hebt letterlijk een thumbsup gegeven op de comment van William om de inputEngine te verplaatsen naar de constructor van Command!?

2020-11-02 09:32 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputEngine.h
> +	T* makeCommand() {
Klopt, maar heb nog geen manier gezien om een generic af te schermen in C++

2020-11-02 09:58 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Input/Commands.cpp
> +Command::Command(InputEngine* _inputEngine) : inputEngine(_inputEngine) {}
Ik heb denk ik een brainfart gehad toen ik deze comment typte. Laatmaar 😆

2020-11-02 10:07 UTC, wieltar commented on engineFoxtrot/Engine/Input/InputEngine.h
> +	T* makeCommand() {
Ik kon geen plek vinden waar dit werd aangeroepen, is dit dan ook echt nodig?

2020-11-02 10:14 UTC, wieltar commented on engineFoxtrot/Engine/Input/InputEngine.h
> +	T* makeCommand() {
scratch that, het was gewoon heel verwarrend 
eigenlijk voert dit deze regel uit:
inputEngine.configure(KEY_A, new MoveLeft(&inputEngine), false);

maar dan via allemaal callbacks naar de engine en niet direct op input, wat ik een beetje vreemd/omslachtig vind tbh maar dat is geen probleem voor nu

Het enige wat hier kan gebeuren is dat ik class Foo(&inputEngine) mee kan geven en dat vind hij helemaal prima, eigenlijk zou input engine dan over moeten erven van command en op dezelfde manier generic moeten beschermen zoals gedaan is in EventSingleton

2020-11-02 10:14 UTC, wieltar commented on engineFoxtrot/Engine/Input/InputEngine.h
> +	T* makeCommand() {
static_assert(std::is_base_of<Event, T>::value, "dispatchEvent Assert fail: Make sure the event that is fired and the Template Type is the same");

2020-11-02 10:52 UTC, Maxvani commented on engineFoxtrot/Engine/Input/Commands.cpp
> +Command::Command(InputEngine* _inputEngine) : inputEngine(_inputEngine) {}
😂😂

2020-11-02 11:03 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputEngine.h
> +	T* makeCommand() {
Is dat niet een compile-time check voor op een class egk?

2020-11-02 11:09 UTC, Maxvani commented on engineFoxtrot/Engine/Input/InputEngine.h
> +	T* makeCommand() {
Nvm werkt ook gwn in een function compile-time

2020-11-02 12:47 UTC, Maxvani commented on engineFoxtrot/Main/main.cpp
> +	engine.configureInput(KEY_A, engine.makeCommand<MoveLeft>());
@ttleeuw dit is gefixt in jouw branch toch? Dan resolve ik hem namelijk

2020-11-02 13:44 UTC, Rinkeeee96 commented
Even updaten met develop. @ttleeuw Kijk jij even naar de comments? Dan kan fps input erin.

2020-11-02 14:07 UTC, Rinkeeee96 approved these changes

2020-11-02 14:18 UTC, Rinkeeee96 approved these changes

2020-11-02 14:42 UTC, TheLarsJansen approved these changes

2020-11-02 14:52 UTC, WilliamRossAvans approved these changes

2020-11-02 14:52 UTC, merged