[WIP] Feature/physics/collision
Rinkeeee96/FoxTrot_SA_Engine pull request #32
Opened 2020-10-29 16:26 UTC by ttleeuw

// TODO
- Code cleanup
- Rotation fix
- Doxygen
- Merge develop

2020-10-30 20:23 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Engine.cpp
> +		physicsEngine.registerObjectInCurrentVectorWithPhysicsEngine();
Dit is niet meer nodig, gefixt na het maken van de layers. Weghalen aub.

2020-10-30 20:24 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsBody.cpp
> +	rotation(object->getRotation()), jumpHeight(object->getJumpHeight()), yAxisVelocity(object->getYAxisVelocity()), rotatable(object->getRotatable()) {
De rotation werkt niet helemaal goed als je de applicatie runt. Voelt niet echt goed aan. misschien even fixen?

2020-11-01 09:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsBody.cpp
> +	rotation(object->getRotation()), jumpHeight(object->getJumpHeight()), yAxisVelocity(object->getYAxisVelocity()), rotatable(object->getRotatable()) {
Wat voelt niet precies goed aan?

2020-11-01 10:42 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.cpp
> +		physicsEngine.registerObjectInCurrentVectorWithPhysicsEngine();
Goed dat je het zegt, ik zie dat layers niet in deze branche zitten en dat hij up-to-date is met develop, Github is weer raar aan het doen.

2020-11-01 10:43 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/Physics/PhysicsBody.cpp
> +	rotation(object->getRotation()), jumpHeight(object->getJumpHeight()), yAxisVelocity(object->getYAxisVelocity()), rotatable(object->getRotatable()) {
Je kan het character op zn kop flippen op een hele makkelijke manier. Voelt niet natuurlijk aan, geen idee hoe of wat dit te fixen is.

2020-11-02 07:27 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsBody.cpp
> +	rotation(object->getRotation()), jumpHeight(object->getJumpHeight()), yAxisVelocity(object->getYAxisVelocity()), rotatable(object->getRotatable()) {
Ik heb de player niet rotatable gezet, dat we dit gedrag niet krijgen, het enige probleem wat ik dan nog zie is het volgende:
![image](https://user-images.githubusercontent.com/31704739/97840954-3fe51b80-1ce5-11eb-865e-b7dcac0bb6c6.png)

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Events/Key/KeyEvent.h
> +	virtual std::string ToString() const { return GetName(); }
std:: mag weg

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Events/Mouse/MouseButtonEvent.h
> +	virtual std::string ToString() const { return GetName(); }
std:: mag weg

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Input/InputEngine.cpp
> +	//}
Iets dat uitgecomment is mag weg toch?

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Input/InputFacade.h
> +#include "./Events/Mouse/MouseScrolledEvent.h"
Volgens mij kan overal de ./ weg

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/ContactListenerAdapter.h
> +#include "./Events/Action/ActionEvent.h"
./ mag weg

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/ContactListenerAdapter.h
> +#include <Physics\PhysicsFacade.h>
<> moeten "" zijn

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/ContactListenerAdapter.h
> +
doxygen boven de class

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsFacade.cpp
>  	// https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_dynamics.html#autotoc_md113
Kan deze link eruit? Is denk ik niet zo mooi op develop

2020-11-02 10:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsFacade.h
> +#define PI 3.14159
Er is ook een C++ ding voor PI dan hoef je hem niet te definen.
https://stackoverflow.com/questions/1727881/how-to-use-the-pi-constant-in-c

2020-11-02 11:15 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/InputEngine.cpp
> +	//}
Heb het voorlopig uitgecommend staan omdat als FPS erin komt er nog gebruikt wordt gemaakt van deze functie. Als fps erin zit zal ik dit omschrijven en verwijderen

2020-11-02 11:35 UTC, Maxvani requested changes
Op het moment blijft het karakter naar een kant lopen bij loslaten van van a of d, ook kan ik een groot deel van de tijd nier springen. Iets fout gegaan met mergen misschien?

2020-11-02 12:39 UTC, closed without merging