[WIP]Particle setup v2
Rinkeeee96/FoxTrot_SA_Engine pull request #33
Opened 2020-10-29 16:29 UTC by Rinkeeee96

2020-10-30 07:50 UTC, ttleeuw requested changes

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Fps/FrameData.h
> +	double framesPerSecond = 0;
Wat is hier gebeurd?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return framesPerSecond;
Wat is hier gebeurd?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/General/GeneralDefines.h
> +#define ONE			1
Waarvoor wordt deze 1/ONE gebruikt, misschien iets specifieker benoemen

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +inline float Rad2Deg(float a)
Rad; Radius? Radiant?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +inline float clampf(float value, float min_inclusive, float max_inclusive)
Niet klassen speciefiek? In de helper functions?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +inline float clampf(float value, float min_inclusive, float max_inclusive)
zelfde geldt voor sommige functies hieronder

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +void Particle::addParticles(int count)
opsplitsen in aparte functies, dit is een lange functie

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +#include "stdafx.h"
Particle PR staat open, brand los zou ik zeggen. Particle.h en ParticleInit.h is een externe library dus daarom geen doxygen, en ook geen facade want dat gaat niet met het over erven naar object.


Kan dit niet anders opgelost worden, dan de daadwerkelijke klassen in het project plakken?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	for (Object * particle : (*pointerToCurrentScene)->getAllObjectsInScene()) {
Is een particle een object, of heeft een object particles?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/ParticleInit.h
> +#pragma once
Zelfde geldt als voor Particle.cpp, kan het niet anders opgelost worden dan externe libraries in het project plakken?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/IVideoFacade.h
> +	virtual void drawParticle(float posX, float startPosX, float posY, float startPosY, float size, float spriteID, float colorR, float colorG, float colorB, float colorA, float rotation) = 0;
Object ipv veel parameters

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +									part->getSpriteID(), partData.colorR, partData.colorG, partData.colorB, partData.colorA, partData.rotation); // TODO Remove hard ID
TODO kan zo te zien weg

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +		videoFacade->drawParticle(	partData.posx, partData.startPosX, partData.posy, partData.startPosY, partData.size,
drawParticle(currentParticle)?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +void VideoFacade::drawParticle(float posX, float startPosX, float posY, float startPosY, float size, float spriteID, float colorR, float colorG, float colorB, float colorA, float rotation)
Object ipv alle variabelen

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoFacade.h
> +	void drawParticle(float posX, float startPosX, float posY, float startPosY, float size, float spriteID, float colorR, float colorG, float colorB, float colorA, float rotation);
object ipv alle variabelen

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Main/main.cpp
> +	auto particle1 = new ParticleInit(11);        // create a new particle system pointer
Beheerd het object zijn particles niet?

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/Main/main.cpp
> +	auto particle1 = new ParticleInit(11);        // create a new particle system pointer
Zorgt ervoor dat het object het aan de hand van state kan zetten
(Jumping, walking etc)

2020-10-30 07:50 UTC, ttleeuw commented on engineFoxtrot/ParticleTest.cpp
> +#include "stdafx.h"
Test class naar develop?

2020-10-30 09:22 UTC, WilliamRossAvans requested changes

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    *seed = *seed * 134775813 + 1;
Random nummer

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        particle_data_[i].c = clampf(b + v * RANDOM_M11(&RANDSEED), 0, 1); \
waar zijn de ze \ voor?

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    }
kan dit niet in 1x tijdens de loop? nu loop je 2x over alle data

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    }
kan dit niet in 1x tijdens de loop? nu loop je 2x over alle data

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        }
kan dit niet in 1x tijdens de loop? nu loop je 2x over alle data

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    }
je kan ook de if in de forloop zetten en daarna particle_data_[i].rotation = -Rad2Deg(dir.getAngle()); uitvoeren. Dat is beter onderhoudbaar als 2x dezelfde loop op 1 regel na

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        }
Probeer dit allemaal in 1 loop te zetten, zal er nu over ophouden als het vaker komt

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        //particle_data_[i].timeToLive = 0.0f;
waarom is dit uitgecommend? als die niet nodig is kan de loop ook weg

2020-10-30 09:22 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +////don't use a transform matrix, this is faster
Waarom blijft het dan staan?

2020-10-30 09:52 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.h
> +	double framesPerSecond = 0;
Dit is de FPS van max en als het goed is niks aan veranderd.
Heb even vergeleken met develop en is het zelfde, GIT is aan het spoken.

2020-10-30 09:52 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return framesPerSecond;
Dit is de FPS van max en als het goed is niks aan veranderd.
Heb even vergeleken met develop en is het zelfde, GIT is aan het spoken.

2020-10-30 09:52 UTC, TheLarsJansen commented on engineFoxtrot/Engine/General/GeneralDefines.h
> +#define ONE			1
Dit is de FPS van max en als het goed is niks aan veranderd.
Heb even vergeleken met develop en is het zelfde, GIT is aan het spoken.

2020-10-30 09:53 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +inline float Rad2Deg(float a)
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele naamgeving hoef aan te passen in een library.

2020-10-30 09:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +inline float clampf(float value, float min_inclusive, float max_inclusive)
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 09:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +void Particle::addParticles(int count)
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 09:55 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +#include "stdafx.h"
Ideeen?

2020-10-30 09:55 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	for (Object * particle : (*pointerToCurrentScene)->getAllObjectsInScene()) {
Particle erft over van Object.

2020-10-30 09:56 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/IVideoFacade.h
> +	virtual void drawParticle(float posX, float startPosX, float posY, float startPosY, float size, float spriteID, float colorR, float colorG, float colorB, float colorA, float rotation) = 0;
Ja maar dan moet de video facade van particle af weten, dat wil ik niet want dan wordt de coupling beetje hoog

2020-10-30 09:57 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +		videoFacade->drawParticle(	partData.posx, partData.startPosX, partData.posy, partData.startPosY, partData.size,
Ja maar dan moet de video facade van particle af weten, dat wil ik niet want dan wordt de coupling beetje hoog

2020-10-30 09:57 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +void VideoFacade::drawParticle(float posX, float startPosX, float posY, float startPosY, float size, float spriteID, float colorR, float colorG, float colorB, float colorA, float rotation)
Ja maar dan moet de video facade van particle af weten, dat wil ik niet want dan wordt de coupling beetje hoog

2020-10-30 09:57 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoFacade.h
> +	void drawParticle(float posX, float startPosX, float posY, float startPosY, float size, float spriteID, float colorR, float colorG, float colorB, float colorA, float rotation);
Ja maar dan moet de video facade van particle af weten, dat wil ik niet want dan wordt de coupling beetje hoog

2020-10-30 09:59 UTC, TheLarsJansen commented on engineFoxtrot/ParticleTest.cpp
> +#include "stdafx.h"
Foutje met verwijderen

2020-10-30 10:00 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    *seed = *seed * 134775813 + 1;
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 10:00 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        particle_data_[i].c = clampf(b + v * RANDOM_M11(&RANDSEED), 0, 1); \
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 10:00 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    }
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 10:00 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    }
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 10:00 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        }
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 10:00 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    }
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 10:00 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        }
Dit is van Particle.cpp en zoals ik op whatsapp gezegd heb wil ik dat beschouwen als een externe lib. Maar kan geen facade omheen vanwege het overerven met project. Lijkt me niet dat ik dan de hele werking of opzet moet aanpassen van een library, want dan ist geen library meer

2020-10-30 10:01 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        //particle_data_[i].timeToLive = 0.0f;
Zal deze ff eruit halen

2020-10-30 10:02 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +////don't use a transform matrix, this is faster
Eruit gehaald

2020-10-30 10:04 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +inline float Rad2Deg(float a)
Dan kan er beter met het adapter patroon gewerkt worden. Anders heb je de daadwerkelijke lib in je project.

2020-10-30 10:06 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +        particle_data_[i].c = clampf(b + v * RANDOM_M11(&RANDSEED), 0, 1); \
Maar als antwoord op de vraag, met de \ geef je aan dat er geen linebreak is dus alles valt onder die define op regel 123

2020-10-30 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +		videoFacade->drawParticle(	partData.posx, partData.startPosX, partData.posy, partData.startPosY, partData.size,
Misschien object een drawableComponentObject laten kennen, dan kun je het object meesturen en in video de drawablecomponents opvragen, dan blijft de koppeling laag, en krijg je niet dat er allemaal parameters meegestuurd hoeven te worden

2020-10-30 10:17 UTC, wieltar requested changes
Ik zie wel een paar punten die beter konden, het begin is er maar sommige functies zijn te groot en onleesbaar, misschien dat je een builder kan gebruikern i.c.m een factory om de particle objecten aan te maken om die leesbaarheid wat te vergroten en om het wat uit elkaar te trekken.

de getters en setters lijken me niet even handig in elke situatie en ik zou opletten met het implementeren van een specifieke "jump particle" implementatie binnen de engine, ik zou dit generiek houden en gewoon een event of wat dan ook afvuren waarmee een particle wordt aangemaakt ipv een functie aanroepen die specifiek een jump particle aanmaakt.

verder zag de basis implementatie er goed uit binnen de game, particles voegen wel echt wat toe maar let op de kwaliteit van de code (en ik zag nog geen jump particle verschijnen, vond ik wel jammer aangezien ik de functie wel zag staan)

sommige stukken lijken op een directe copy paste en bevatten veel uitgecommentarieerde code die me niet alijtd nodig lijkt


ik kijk nu nog eens door de code en kan de jump functie zo 1..2..3 niet meer vinden, als dit als je weggehaald dan kan je dat stukje negeren ;)

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +class ParticleData
ik zie op sommige plekken dat er losse variablen worden meegegeven aan functies, kunnen we daar niet in eisen dat dat deze struct is of is dat iets wat we niet willen?

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +    float r = 0, g = 0, b = 0, a = 0;
kunnen deze duidelijker

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +    unsigned int atlasIndex = 0;
de fuc is een atlasIndex?

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +    void resetSystem();
standaardiseren binnen engine

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +    virtual void setGravity(const Vec2& g);
als de struct al public is en we er al bij kunnen waarom hebben we dan getters en setters? Stel een programmeur wil otf iets aanpassen in zijn particle struct, moet dat dan niet gewoon meteen kunnen (en hij kan er nu toch al bij?)

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if ((*pointerToCurrentScene)->getAllObjectsInScene().size() == 0) return;
lopen we nu niet over alle objecten in de scene heen en halen we nu ook niet de "niet particles op"?? hoe valideer je hierop en zorg je dat dit niet stuk loopt

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.h
> +#include "../SceneManager/Scene.h"
relatieve paden

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleInit.cpp
> +void ParticleInit::setStyle(PatticleStyle style)
deze functie is gigantisch en niet erg leesbaar

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	bool isParticle = false;
wat nou als ik zeg mijn speler is een particle en ik gebruik hem gewoon als speler, dan kan je zeggen dat moet je niet doen maar ik zou dit niet bijhouden in de object base class, wat ik hierboven al zei met de validatie van het ophalen van al je objecten in de scene, hoe valideer je dit aangezien de afhankelijkheid van de scenemanager groot is moeten we hier goed over nadenken

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +#include "../ParticleSystem/ParticleInit.h"
relatieve paden

2020-10-30 10:17 UTC, wieltar commented on engineFoxtrot/Engine/Video/IVideoFacade.h
> +	virtual void drawParticle(float posX, float startPosX, float posY, float startPosY, float size, float spriteID, float colorR, float colorG, float colorB, float colorA, float rotation) = 0;
+1 stuur gewoon het object mee

2020-10-30 10:49 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Engine.cpp
> +	particleEngine.pointerToCurrentScene = &sceneManager.currentScene;
een init functie maken die aangeroepen wordt in de constructor is toch precies hetzelfde als het in de constructor zetten?
of wil je hem dan niet in de constructor aanroepen?

2020-10-30 10:50 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	chrono::duration<double> diff = chrono::duration_cast<chrono::duration<double>>(endTime - startTime);
FPS is van Max en GIT is aan het spoken.
Is niks veranderd dus voor feedback op FPS moet je bij Max zijn

2020-10-30 10:50 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.h
> +	list<chrono::duration<double>> frametimes;
FPS is van Max en GIT is aan het spoken.
Is niks veranderd dus voor feedback op FPS moet je bij Max zijn

2020-10-30 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.h
> +	double framesPerSecond = 0;
Voor feedback op FPS moet je dus bij Max zijn

2020-10-30 10:54 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return framesPerSecond;
Voor feedback op FPS moet je dus bij Max zijn

2020-10-30 11:09 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +    virtual void setGravity(const Vec2& g);
de struct is protected dus niet public

2020-10-30 11:11 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +    virtual void setGravity(const Vec2& g);
Oh w8 ik zie nu wat je bedoelt

2020-10-30 11:13 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if ((*pointerToCurrentScene)->getAllObjectsInScene().size() == 0) return;
Er staat een if statement in de for loop die controleert of het een particle is of niet, dus ja we lopen over alles heen maar als het geen particle is wordt ie overgeslagen

2020-10-30 11:15 UTC, wieltar commented on engineFoxtrot/Engine/Engine.cpp
> +	particleEngine.pointerToCurrentScene = &sceneManager.currentScene;
in de init zou je verdere aditonele parameters kunnen stoppen die voor elk systeem zijn, plus zo kan je er dus voor zorgen dat de volgorde waarin je systemen opstart en afsluit / opruimt wordt afgedwongen

je legt dan ook de verantwoordelijkheden bij de classes/engines zelf wat ze met de meegegeven paramters moeten doen,nu gebeurd dat in de constructor van de engine en dat is minder schaalbaar/foutgevoeliger omdat je hier dan in een keer alle start up logica van elk systeem/engine dingetje krijgt

2020-10-30 11:15 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.h
> +    unsigned int atlasIndex = 0;
Heb hem eruit gehaald. Is voor een sprite sheet. Maar dat kan straks via Williams zijn stuk gaan

2020-10-30 11:50 UTC, TheLarsJansen commented on engineFoxtrot/Engine/ParticleSystem/Particle.cpp
> +    for (int i = start; i < _particleCount; ++i)
De for loop voor size is een andere forloop dan die voor color

2020-11-02 10:23 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	bool isParticle = false;
Je kan dit niet verwerken in Particle. Beter is dan om er een const van te maken en niet de mogelijkheid geven om dit aan te passen. In de constructor van Particle wordt hij dan wel gezet. Dat zou de oplossing zijn.

2020-11-02 10:46 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Object.h
> +	bool isParticle = false;
@wieltar omgebouwd. In Object zit nu een protected constructor die alleen toegankelijk is voor Particle. Zo kun je geen objecten aanmaken die particle zouden zijn.

2020-11-02 14:50 UTC, wieltar approved these changes

2020-11-02 15:20 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return framesPerSecond;
@wieltar Dit gebeurd al in aparte lijsten aangezien de game fps en render fps allebei berekend worden door een apart FrameData object

2020-11-02 15:21 UTC, Maxvani commented on engineFoxtrot/Engine/Fps/FrameData.cpp
> +	return framesPerSecond;
Het is geen singleton

2020-11-02 15:24 UTC, Maxvani approved these changes

2020-11-02 15:31 UTC, TheLarsJansen approved these changes

2020-11-02 15:31 UTC, merged