Change sprites
Rinkeeee96/FoxTrot_SA_Engine pull request #34
Opened 2020-10-30 09:00 UTC by WilliamRossAvans

A pr for the new sprites.

2020-10-30 10:19 UTC, ttleeuw approved these changes

2020-10-30 13:36 UTC, TheLarsJansen approved these changes

2020-10-30 13:36 UTC, TheLarsJansen commented
Heb er niet naar gekeken, ga der op goed vertrouwen vanuit dat het goed is :)

2020-10-30 20:28 UTC, Rinkeeee96 requested changes
Er staat nog cpp bestanden in de lijst van changes. Die horen hier niet tussen te staan!

2020-11-01 09:55 UTC, Rinkeeee96 approved these changes

2020-11-01 09:55 UTC, merged