Dll builld
Rinkeeee96/FoxTrot_SA_Engine pull request #36
Opened 2020-10-30 12:26 UTC by Maxvani

Let op: De assets folder is verplaatst naar de game (Glitch) voor de volledige build

2020-10-30 13:29 UTC, TheLarsJansen commented
![image](https://user-images.githubusercontent.com/43005884/97710667-58262200-1abc-11eb-8b7b-9433608b984a.png)

Deze error al gehad?

2020-10-30 13:49 UTC, TheLarsJansen submitted a review, later dismissed

2020-10-30 13:49 UTC, TheLarsJansen commented on engineFoxtrot/Engine/General/GeneralDefines.h
> +//#define DLLEXPORT   __declspec( dllexport )
Uitcommenten of weg?

2020-10-30 13:49 UTC, TheLarsJansen commented on engineFoxtrot/Engine/FileParser/FileParser.h
> +#include "core.h"
Als core.h overal nodig is kan die dan niet beter in de PCH?

2020-10-30 13:49 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Physics/PhysicsFacade.h
> +#include "box2d/box2d.h"
Deze mag niet meer in de .h volgens mij. Merge foutje?

2020-10-30 13:49 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Object.h
> +#include "stdafx.h"
PCH in de .h of .cpp? .cpp toch?

2020-10-30 13:49 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/SceneManager.cpp
> +#include "core.h"
core.h in de .cpp of .h? Zie het nu op plekken verschillen?

2020-10-30 13:49 UTC, TheLarsJansen commented on Glitch/Glitch.h
> +#include "../engineFoxtrot/api.h"
Relatief pad?

2020-10-30 20:26 UTC, Rinkeeee96 requested changes
Programma bouwt niet en heeft een shit ton aan warnings. Dat gaat zo develop niet op.

2020-11-01 10:07 UTC, ttleeuw submitted a review, later dismissed

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/General/GeneralDefines.h
> +//#define DLLEXPORT   __declspec( dllexport )
#define EXPORT kan volgens mij ook weg

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Physics/PhysicsFacade.h
> +#include "box2d/box2d.h"
Is opgelost in de physics branche, maar ik zou het wel laten hoe het eerst stond als het kan, zodat er geen merge conflicten etc op komen

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Structs/fpsStructs.h
> +struct API TextSize
Misschien even kijken of dit wel een EXPORT nodig heeft

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Structs/fpsStructs.h
> +struct API TextPosition
Misschien even kijken of dit wel een EXPORT nodig heeft

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Structs/fpsStructs.h
> +struct API FpsMessage
Misschien even kijken of dit wel een EXPORT nodig heeft

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/InputConstants.h
> +enum API State
Misschien even kijken of dit wel een EXPORT nodig heeft

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/InputConstants.h
> +enum API Action
Misschien even kijken of dit wel een EXPORT nodig heeft

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/InputConstants.h
> +enum API InputType
Misschien even kijken of dit wel een EXPORT nodig heeft

2020-11-01 10:07 UTC, ttleeuw commented on engineFoxtrot/Engine/Input/Commands.h
> +class API MoveLeft : public Command
Misschien even kijken of dit wel een EXPORT nodig heeft, (Wordt naar game verplaatst, maar zit in physics brance)

2020-11-02 13:11 UTC, wieltar commented on engineFoxtrot/Engine/FileParser/FileParser.h
> +#include "core.h"
Kan, we hadden het in 1e instantie weggelaten i.v.m classes die niet geexporteerd hoeven te worden

2020-11-02 13:21 UTC, wieltar commented on engineFoxtrot/Engine/FileParser/FileParser.h
> +#include "core.h"
sommige classes zoals layer hebben ook geen .cpp voor de precompiled header + ik zie nu dat ik circular depencencies krijg..?

2020-11-02 13:25 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Object.h
> +#include "stdafx.h"
dit is denk ik een wat diepgaander probleem, zodra ik hem hier weghaal klapt het stuk in soundfacade terwijl de volgorde van includes (dus eerst precompiled header en dan de rest) wel goed gaat

2020-11-02 13:28 UTC, wieltar commented on engineFoxtrot/Engine/SceneManager/Object.h
> +#include "stdafx.h"
lossen we op na de oplevering

2020-11-02 13:29 UTC, wieltar commented on Glitch/Glitch.h
> +#include "../engineFoxtrot/api.h"
was niet mogelijk omdat het solution directory niet als aditional include is gegeven, deze gaan nu op project niveau

2020-11-02 13:32 UTC, wieltar commented on Glitch/Glitch.h
> +#include "../engineFoxtrot/api.h"
> 
> 
> Programma bouwt niet en heeft een shit ton aan warnings. Dat gaat zo develop niet op.

dit komt dus nu allemaal naar voren omdat nu pas dit project als concrete dll wordt gebouwd, dus 1 ja dit moet eruit 2 dit was iets dat eerder moest maar ik weet niet wat de impact is van deze waarschuwingen om ze z.s.m op te lossen

het komt basically neer op foute 1e development keuzes maar we kijken wat we ermee kunnen aangezien het waarschuwingen zijn

2020-11-02 17:27 UTC, Maxvani commented on Glitch/Glitch.h
> +#include "../engineFoxtrot/api.h"
Maar basically alle warnings zijn nu gefixt dus het is helemaal goed

2020-11-02 18:34 UTC, ttleeuw approved these changes

2020-11-02 19:02 UTC, Rinkeeee96 approved these changes

2020-11-02 19:03 UTC, TheLarsJansen approved these changes

2020-11-02 19:03 UTC, merged