[WIP] Feature/moving camera
Rinkeeee96/FoxTrot_SA_Engine pull request #61
Opened 2020-11-09 13:12 UTC by Rinkeeee96

2020-11-12 09:03 UTC, ttleeuw requested changes
Stel ik heb een heel hoog level; 
![image](https://user-images.githubusercontent.com/31704739/98918683-3706fd80-24ce-11eb-81a1-8014f487c931.png)

Momenteel als ik val beweegt de Y niet mee, ik snap de achterliggende gedachten (in gat vallen = dood). Alleen het geval hierboven beschreven is niet meer mogelijk

2020-11-12 09:03 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	int sceneWidth = WINDOW_WIDTH;
Krijg je dit niet mee als param?

2020-11-13 08:50 UTC, TheLarsJansen commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	int sceneWidth = WINDOW_WIDTH;
Nee de sceneWidth is iets anders dan de WINDOW_WITH.
De WINDOW_WITH is 1920, dus de breedte van het "fysieke" scherm.
De sceneWidth is de breedte van de scene/level.
Hierdoor kan jouw eerste comment wel, zal het bij de standup uitleggen

2020-11-13 08:57 UTC, WilliamRossAvans reviewed
Helemaal op het einde van een level kan je 'uit het level' lopen lijkt het
Net daarvoor lijkt het of er een ontzichtbaar blok staat wat je tegenhoud
Afbeelding kan ik niet in de commend plaatsen op een of andere manier, zie app ;)

2020-11-13 10:01 UTC, ttleeuw approved these changes

2020-11-13 10:03 UTC, Maxvani approved these changes

2020-11-13 10:46 UTC, wieltar approved these changes

2020-11-13 10:52 UTC, merged