[draft] Menu
Rinkeeee96/FoxTrot_SA_Engine pull request #63
Opened 2020-11-09 14:10 UTC by wieltar

2020-11-11 13:53 UTC, TheLarsJansen commented
Deze branch heeft de fix voor Issue #58 ook toch? Wou hem even linken maar weet niet hoe dat moet dus moet iemand anders even doen :)

2020-11-13 09:17 UTC, ttleeuw requested changes

2020-11-13 09:17 UTC, ttleeuw commented on Glitch/Game/MainMenu.cpp
> +#define MAX_X 1920
is dit altijd zo?

2020-11-13 09:17 UTC, ttleeuw commented on Glitch/Game/MainMenu.h
> +	MainMenu() : Scene(1) {};
hardcoded?

2020-11-13 09:17 UTC, ttleeuw commented on Glitch/Game/Player/Player.cpp
> +Player::Player(int _id): Drawable(_id) {
Hoe gaat dit met multiple inheritance?

2020-11-13 09:17 UTC, ttleeuw commented on Glitch/Glitch.cpp
> +void TestMainMenu() {
Scene specific manager in game, zodat deze verantwoordelijk is voor het wisselen van scene?

2020-11-13 09:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.cpp
> +	EventListners();
EventListeners

2020-11-13 09:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.cpp
> +void Engine::EventListners() {
EventListeners

2020-11-13 09:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Engine.h
> +	API void EventListners();
EventListeners

2020-11-13 09:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Events/EventType.h
> +	LoadSprite,
Is het wel efficient om dit met events te doen, veel eventlisteners om over te loopen

2020-11-13 09:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Events/Video/VideoLoadSpriteEvent.h
> +class VideoLoadSpriteEvent : public Event
Is het wel efficient om dit met events te doen, veel eventlisteners om over te loopen

2020-11-13 09:17 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Button.h
> +class API Button : public Drawable
Algemeen mapje in scenemanger of daarbuiten, objects?

2020-11-13 09:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Structs/HelperStructs.h
> +struct ColoredString
ColoredText misschien duidelijker

2020-11-13 10:13 UTC, wieltar commented on engineFoxtrot/Engine/Events/EventType.h
> +	LoadSprite,
Het valt wel mee hoeveel listeners we hebben, dat zijn alleen de engines zelf. Dit gebeurd hier op dezelfde manier als bij sound in een level, registreren is inladen omdat de scene meteen in zijn geheel wordt aangemaakt.

2020-11-13 10:17 UTC, ttleeuw commented on engineFoxtrot/Engine/Events/EventType.h
> +	LoadSprite,
Is dat wel zo? Iedere enemy, player enzo zijn allemaal listeners

2020-11-13 12:55 UTC, Rinkeeee96 commented on Glitch/SceneSwitcher/SceneSwitcher.h
> +	map<string, Scene*> scenes;
Je bent nu dubbel alle scenes aan het registreren? Kun je dit niet anders regelen? Dat binnen de game we niet direct interact met de scenemanager maar dat de sceneswitcher een soort interface wordt naar de scenemanager?

2020-11-13 12:58 UTC, ttleeuw commented on Glitch/SceneSwitcher/SceneSwitcher.h
> +	map<string, Scene*> scenes;
Klopt, alleen nu is er een klassen verantwoordelijk voor het bijhouden van gamespecifieke schermen en het wisselen van game specifieke scenen, Na level A volgt altijd LoadingScene waarnaar de overworld scene geladen moet worden

2020-11-15 14:14 UTC, Rinkeeee96 requested changes
Algemene opmerking
Doxygen. Mist namelijk overal

2020-11-15 16:56 UTC, Rinkeeee96 requested changes
Knoppen blijven actief tijdens de game. Je kan tijdens de game weer opnieuw op play drukken als je de muis op zelfde plek houdt

2020-11-16 10:10 UTC, ttleeuw approved these changes

2020-11-16 10:30 UTC, ttleeuw approved these changes

2020-11-16 10:31 UTC, WilliamRossAvans approved these changes

2020-11-16 10:54 UTC, Rinkeeee96 approved these changes

2020-11-16 10:54 UTC, merged