Particles Pos and Object pos are now shared
Rinkeeee96/FoxTrot_SA_Engine pull request #66
Opened 2020-11-09 19:37 UTC by Rinkeeee96

Fix of issue report [Issue](https://github.com/Rinkeeee96/FoxTrot_SA_Engine/issues/43)

2020-11-09 19:45 UTC, Rinkeeee96 commented
Uitleg over de extra functie in Particle Engine.

Aangezien particle als een object in de lijst zit en ook zo aangesproken kan worden. Maar de X en Y locatie niet geupdate worden in Particle wanneer de Object location geset wordt check ik bij het updaten van de particle of deze posities anders zijn. Zo ja dan update ik de Particle position met de Object position, deze is leidend.

2020-11-09 19:46 UTC, Rinkeeee96 commented
Graag ook even naar deze issue kijken, zou ik die eventueel meteen kunnen meenemen
[Issue](https://github.com/Rinkeeee96/FoxTrot_SA_Engine/issues/42)

2020-11-10 08:39 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
staat dit niet al in de for loop hierboven?

2020-11-10 08:41 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
+1

2020-11-10 08:41 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
of wordt hier gekeken of het particle dat je meestuurt matched met de particle in de adapter? Is dat eveneens niet een beetje overbodig of zie ik dat verkeerd?

2020-11-10 08:43 UTC, wieltar requested changes
de !particle check lijkt me een beetje overbodig aangezien er bovenaan al wordt gekeken of er een particle wordt 'meegegeven'

2020-11-10 08:43 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
Zie mijn comments op deze PR. Denk dat jullie die niet gezien hebben

2020-11-10 08:45 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
![image](https://user-images.githubusercontent.com/10192977/98650613-6df7da80-2339-11eb-82cf-fbe2359e30e7.png)

2020-11-10 08:47 UTC, ttleeuw commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
![image](https://user-images.githubusercontent.com/31704739/98650811-b1524900-2339-11eb-9ac1-3d5cfb5515f9.png)
Maar weet je hier niet al of het een particle is?

2020-11-10 09:18 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
Deze check wordt uitgevoerd op een pointer. Als die leeg is returned hij. Hij kijkt niet of het een particle is. 
Dit is puur om een nullptr af te vangen

2020-11-10 09:56 UTC, wieltar commented on engineFoxtrot/Engine/ParticleSystem/ParticleEngine.cpp
> +	if (!particle)
kunnen we dan niet beter zeggen dat we wer een reference of een const ref van maken? of gaat dat dan niet?

2020-11-10 10:07 UTC, wieltar approved these changes

2020-11-10 11:31 UTC, ttleeuw approved these changes

2020-11-10 11:31 UTC, WilliamRossAvans approved these changes

2020-11-10 11:31 UTC, merged