[W.I.P] Issue fixes
Rinkeeee96/FoxTrot_SA_Engine pull request #78
Opened 2020-11-13 13:52 UTC by TheLarsJansen

2020-11-15 12:06 UTC, Rinkeeee96 commented on Glitch/Glitch.cpp
> +	try {
Als je hier een try catch neerzet dan moet je eig ook ff in de engine alle try catches weghalen. Dan hou je deze alleen opt hoogste niveau. Anders heeft t weinig nut.

2020-11-15 12:07 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	void setPlayerObjectID(const int _playerObjectID) { playerObjectID = _playerObjectID; }
Willen we dit wel in de scene/level regelen? Wat de camera volgt.

2020-11-15 12:08 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	void setPlayerObjectID(const int _playerObjectID) { playerObjectID = _playerObjectID; }
Misschien sws anders noemen. Want het nu van dit zou zijn om dit object te volgen. Zou ook een enemy kunnen zijn bijvoorbeeld.

2020-11-15 13:04 UTC, WilliamRossAvans requested changes

2020-11-15 13:04 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	int playerObjectID = 0;
Is het niet beter om een referentie maken naar de player ipv het id

2020-11-15 17:02 UTC, Rinkeeee96 commented on engineFoxtrot/Engine/SceneManager/Scene.h
> +	int getObjectToFollowID() const { return objectToFollow->getObjectId(); }
Zou hier wel een check uitvoeren of objectToFollow niet leeg is.

2020-11-16 09:00 UTC, Rinkeeee96 approved these changes

2020-11-16 09:00 UTC, wieltar approved these changes

2020-11-16 09:02 UTC, WilliamRossAvans submitted a review, later dismissed

2020-11-16 09:13 UTC, Rinkeeee96 approved these changes

2020-11-16 09:23 UTC, WilliamRossAvans approved these changes

2020-11-16 09:23 UTC, wieltar approved these changes

2020-11-16 09:23 UTC, merged