Feature/level fix
Rinkeeee96/FoxTrot_SA_Engine pull request #79
Opened 2020-11-15 14:09 UTC by ttleeuw

2020-11-15 14:27 UTC, Rinkeeee96 submitted a review, later dismissed
Doxygen!

2020-11-15 14:31 UTC, Rinkeeee96 commented on Glitch/Game/Levels/Builders/LevelBuilderDirector.cpp
> +	try {
Beetje nutteloze try catch. Wanneer er een error opgegooid wordt wordt hier verder niks mee gedaan. Programma gaat gwn door

2020-11-15 14:31 UTC, Rinkeeee96 commented on Glitch/Game/Levels/Level.h
> +	virtual void OnDetach() override;
inconsistent rename

2020-11-15 14:40 UTC, WilliamRossAvans reviewed
En denk nog aan doxygen

2020-11-15 14:40 UTC, WilliamRossAvans commented on Glitch/Game/Factories/CharacterFactory.h
> +	std::map<std::string, ICharacter*> keyValues;
andere naamgeving zoals characters

2020-11-15 14:40 UTC, WilliamRossAvans commented on Glitch/Game/Factories/CharacterFactory.h
> +			spriteObjectMap.insert(std::pair<std::string, std::map<SpriteState, SpriteObject*>>(name, _spriteObjectMap));
Je kan de spriteobjecten toch al gekoppeld hebben bij je characters

2020-11-15 14:40 UTC, WilliamRossAvans commented on Glitch/Game/Factories/CharacterFactory.h
> +			std::map<SpriteState, SpriteObject*>::iterator it = sprites.begin();
als je characters van te voren registreerd met spriteobjecten hoe je deze later niet meer te koppelen

2020-11-15 14:40 UTC, WilliamRossAvans commented on Glitch/Game/Factories/CharacterFactory.h
> +	ICharacter* create(std::string name, int id) {
Zou de logica in de .cpp zetten ipv .h

2020-11-15 14:40 UTC, WilliamRossAvans commented on Glitch/Game/Game.cpp
> +	builderDirector.construct(&levelOneBuilder);
Zou vanuit 'buiten' aangeven welke file je gaat builden. en niet vanuit construct.
Je krijgt dan een 
`void LevelBuilderDirector::construct(ILevelBuilder* builder) {
	this->currentBuilder = builder;
}`
en 
```
void LevelBuilderDirector::construct(string path) {
	nlohmann::json json;

	try {
		auto filestream = fileLoader.readFile(path);
```

2020-11-15 14:40 UTC, WilliamRossAvans commented on Glitch/Game/Game.cpp
> +	auto levelOne = levelOneBuilder.getLevel();
Zou hier pas 
	`engine.insertScene(levelOne);`
uitvoeren ipv in de builder, dit omdat dit minder fout gevoelig is op het moment dat je een nieuwe builder maakt

2020-11-15 14:40 UTC, WilliamRossAvans commented on Glitch/Game/Levels/Builders/LevelBuilder.cpp
> +			if (objectPropertyValue["name"] == "friction") {
Gebruik hier ook else if net als in createLevel

2020-11-15 14:40 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Engine.cpp
> +	this->videoEngine.attachCamera(objectId);
Zou dit koppelen doormiddel van een ref naar een object en niet naar het objectID

2020-11-15 14:40 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/FileParser/FileLoader.cpp
> +	bool exists = std::filesystem::exists(path); // TODO dynamic fonts
remove comment?

2020-11-15 14:40 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +		calculateOffset(*(*pointerToCurrentScene)->getObject(cameraObjectId), (*pointerToCurrentScene)->getSceneWidth(), (*pointerToCurrentScene)->getSceneHeight());
Als cameraobjectid een ref naar het object hoeft het object niet meer opgezocht te worden

2020-11-15 16:16 UTC, ttleeuw commented on Glitch/Game/Factories/CharacterFactory.h
> +			std::map<SpriteState, SpriteObject*>::iterator it = sprites.begin();
Morgen hier even over bellen, denk dat dit complexer of moeilijker onderhoudbaar wordt

2020-11-15 20:04 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Engine.cpp
> +	this->videoEngine.attachCamera(objectId);
Dit is al gefixd in #78

2020-11-15 20:04 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +		calculateOffset(*(*pointerToCurrentScene)->getObject(cameraObjectId), (*pointerToCurrentScene)->getSceneWidth(), (*pointerToCurrentScene)->getSceneHeight());
Dit is al gefixd in #78

2020-11-16 16:11 UTC, wieltar commented on Glitch/Game/Factories/CharacterFactory.cpp
> +void CharacterFactory::registerCharacter(std::string name, ICharacter* character, std::map<SpriteState, SpriteObject*> _spriteObjectMap) {
(const?) ref

2020-11-16 16:11 UTC, wieltar commented on Glitch/Game/Factories/CharacterFactory.h
> +	void registerCharacter(std::string name, ICharacter* character, std::map<SpriteState, SpriteObject*> _spriteObjectMap);
(const?) ref

2020-11-16 16:12 UTC, wieltar requested changes
const / ref correctness en eventueel sommige doxygen dingen, alvast vooruit lopend op de discussie van morgen

2020-11-16 16:32 UTC, WilliamRossAvans requested changes

2020-11-16 16:32 UTC, WilliamRossAvans commented on Glitch/Game/IGameObject.h
> +	IGameObject() : Drawable(-1) {}
Hardcoded ID is niet de bedoeling

2020-11-16 16:32 UTC, WilliamRossAvans commented on Glitch/Game/Levels/Builders/LevelBuilder.cpp
> +// TODO fix particles
Is dit nog steeds zo?

2020-11-16 16:32 UTC, WilliamRossAvans commented on Glitch/Game/Levels/LoadLevelFacade.h
> +				std::cout << "Something went wrong parsing the file, make sure the file is correctly structured" << "\n";
std:: is niet meer nodig toch?

2020-11-16 16:32 UTC, WilliamRossAvans commented on engineFoxtrot/Engine/Video/VideoFacade.cpp
> +	if (spriteObject.getFileName() == NULL) throw std::exception(ERRORCODES[ERROR_CODE_SVIFACADE_FILENAME_IS_NULL]);
std kan weg

2020-11-16 17:52 UTC, ttleeuw commented on Glitch/Game/Factories/CharacterFactory.h
> +	void registerCharacter(std::string name, ICharacter* character, std::map<SpriteState, SpriteObject*> _spriteObjectMap);
Gaat hier niet ivm gelijk doorgeven als param

2020-11-16 17:52 UTC, ttleeuw commented on Glitch/Game/Factories/CharacterFactory.cpp
> +void CharacterFactory::registerCharacter(std::string name, ICharacter* character, std::map<SpriteState, SpriteObject*> _spriteObjectMap) {
Gaat hier niet ivm gelijk doorgeven als param

2020-11-17 10:09 UTC, wieltar commented on Glitch/Game/Levels/LoadLevelFacade.h
> +				std::cout << "Something went wrong parsing the file, make sure the file is correctly structured" << "\n";
staat bijna overal waar dit wordt gedaan toch?

2020-11-17 10:10 UTC, wieltar submitted a review, later dismissed

2020-11-17 16:20 UTC, WilliamRossAvans approved these changes

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Slime.h
> +	virtual void onUpdate() override {
Wat doet virtual override?
Virtual betekent dat het ergens overriden kan worden.
override betekent dat ie een virtual override.
Kan je dit mij toelichten?

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Characters/Enemies/Slime.h
> +		Object::setYAxisVelocity(val);
Ik zat te kijken naar hoe je deze functie callde.
Ik begrijp wat er gebeurt maar 2 functies met dezelfde naam is niet iets wat je graag wilt.
Toen ging ik kijken naar de route om bij object te komen.
HOLY SHIT wat lijdt dit ver af. Kan dit niet simepeler?
Ik bedoel dan dat slime van IEnemy overerft,
IEnemy van ICharacter, en zo nog een stuk verder

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Characters/ICharacter.h
> +protected:
Protected of private?

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Characters/Player/Player.cpp
> +void Player::setXAxisVelocity(const float val) {
Hier heb je weer een functie met dezelfde naam op een andere plek.
Ik snap hoe het bedoelt is maar dit is best gevoelig voor compiler en menselijke fouten

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Characters/Player/Player.h
> +#include <Engine\Events\Action\ObjectStopEvent.h>
Alles wat je van de engine in de game wil hebben moet via api.h lijkt mij toch

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Factories/CharacterFactory.h
> +#include <exception>
Hier is de PCH voor

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Factories/CharacterFactory.h
> +#include <Engine.h>
Engine includen is volgens mij echt een no no. api includen

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/General/GameErrorCodes.h
> +static const char* GAME_ERRORCODES[] =
api.h export ook de engine error codes. Hoe weten we in een try catch nu of het een game of een engine error is?

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Levels/Builders/ILevelBuilder.h
> +#include <nlohmann\json.hpp>
Engine ding voor api.
En is er een manier om nlohmann hier niet te includen want dit lekt nu door naar de game

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Levels/Builders/LevelBuilder.h
> +	// TODO Fix tileId in tilesets
Kom hier en daar best veel TODO's tegen.
Zijn die al gedaan?
Worden dit issue's?

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Levels/Builders/LevelBuilderDirector.cpp
> +LevelBuilderDirector::LevelBuilderDirector(Engine& engine) { }
De constructor krijgt een engine mee om er vervolgens niks mee te doen

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.h
> +#include <api.h>
api.h staat in de PCH

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Levels/Level.h
> +#include <api.h>
kijk hier ook even naar de game includes

2020-11-17 19:52 UTC, TheLarsJansen commented on Glitch/Game/Levels/LoadLevelFacade.h
> +		catch (exception e) {
Als deze try catch een error throwt wat gebeurt er dan?
Hij heeft dan geen level geladen maar het programma gaat gewoon door volgens mij zonder level.
Wat gebeurt er dan?

2020-11-17 19:52 UTC, TheLarsJansen commented on engineFoxtrot/Engine/FileParser/FileLoader.h
> +class API FileLoader
Waarom hebben jullie ervoor gekozen om de engine het bestand te laten lezen en de game het te laten behandelen?
Was het niet makkelijker om de game het dan ook te laten lezen?

2020-11-17 19:52 UTC, TheLarsJansen commented on engineFoxtrot/Engine/FileParser/FileLoader.h
> +#include <map>
PCH dingen

2020-11-17 19:52 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Input/InputEngine.cpp
> +    }
Volgens mij staan hier allemaal spaties als spacers maar gebruikelijk is tabjes

2020-11-17 19:52 UTC, TheLarsJansen commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +void VideoEngine::attachCamera(const int objectId)
Een fix staat al op develop volgens mij. Kijk hier even goed naar

2020-11-17 19:59 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Slime.h
> +	virtual void onUpdate() override {
Om de optie open te houden, dat er een jump slime en een walk slime of iets dergelijks komt

2020-11-17 20:00 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Slime.h
> +		Object::setYAxisVelocity(val);
Kan, echter moet zit er wel verschil tussen de objecten, characters bevatten AI gameObject is het obvject met algemene game specieke logica en IEnemy voor enemy uitbreidingen

2020-11-17 20:02 UTC, ttleeuw commented on Glitch/Game/Characters/ICharacter.h
> +protected:
Protected, character speciefieke properties

2020-11-17 20:09 UTC, ttleeuw commented on Glitch/Game/Characters/Player/Player.cpp
> +void Player::setXAxisVelocity(const float val) {
Zelfde naam? Player heeft xAxis en yAxis en hier moeten anderewe dingen gebeuren. Of zelfde naam is als in base class? Nadeleen van polymorphisme

2020-11-17 20:13 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.h
> +		catch (exception e) {
Eigenlijk is dit een message voor de developer, het liefste zou je dit terug willen koppelen aan de gebruiker met een message box alleen deze functionaliteit hebben wij niet

2020-11-17 20:14 UTC, ttleeuw commented on Glitch/Game/Levels/LoadLevelFacade.h
> +		catch (exception e) {
En de error moet ergens afgevangen worden, dit zou door een higher level module moeten gebeuren; in dit gevak in de game bij het inladen (en niet in engine)

2020-11-17 20:16 UTC, ttleeuw commented on engineFoxtrot/Engine/FileParser/FileLoader.h
> +class API FileLoader
Het idee is/was zowel de engine als de game moet files inladen eigenlijk wil je alles inladen ook in de engine met behulp van deze methode. Uitlezen van bestand is lower level en wil je dan ook in de engine en kan dan door zowel de engine zelf als de game gebruikt worden

2020-11-17 20:18 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +void VideoEngine::attachCamera(const int objectId)
Zal het morgen controleren, maar dacht dat de fix op develop niet meer klopten; main menu geen speler, geen camera; level wel een speler, ook een camera. Zo stond het volgens mij nog niet op develop

2020-11-17 20:35 UTC, ttleeuw commented on Glitch/Game/Levels/Builders/ILevelBuilder.h
> +#include <nlohmann\json.hpp>
Engine game voor api zal ik verwerken, game heeft sws een referentie naar nlohmann. Engine weet niks af van wat voor file hij read; game specifiek

2020-11-17 22:53 UTC, Rinkeeee96 reviewed
Zie dat jullie ook de camera zetten in de engine. Dit hoeft niet meer aangezien dit binnen een scene geregeld wordt. Dus even dubbele functionaliteit eruit halen

2020-11-17 22:54 UTC, Rinkeeee96 reviewed
Volgende keer beter letten op de scope van de PR. Er zit teveel extra functionaliteit in deze PR.

2020-11-18 07:10 UTC, ttleeuw commented on Glitch/Game/Characters/Enemies/Slime.h
> +	virtual void onUpdate() override {
Na iets langer overdenken, eruit gehaald ivm te veel rekening houden met toekomst, en kan voor problemen zorgen

2020-11-18 07:11 UTC, ttleeuw commented on Glitch/Game/Characters/Player/Player.h
> +#include <Engine\Events\Action\ObjectStopEvent.h>
Nogmaals over het game project gelopen en overal waar de api.h in de de .h geinclude stond aangepast omdat dit ook in de precompiled header staat

2020-11-18 07:13 UTC, ttleeuw commented on engineFoxtrot/Engine/Video/VideoEngine.cpp
> +void VideoEngine::attachCamera(const int objectId)
Goed gezien, was een oude niet meer gebruikte functie ivm scene

2020-11-18 07:22 UTC, ttleeuw commented on Glitch/Game/General/GameErrorCodes.h
> +static const char* GAME_ERRORCODES[] =
Dit zijn de "higher" level error codes, de exception binnen de engine moeten binnen game worden afgevangen en hierop specifiek geanticipeerd worden. Het maakt voor bv de gebruiker niet uit of een image not found, txt bestand not found enzo niet uit. Het voor de gebruiker alleen belangrijk om te weten dat er iets mis is gegaan met een bestand laden

2020-11-18 10:26 UTC, TheLarsJansen approved these changes

2020-11-18 11:12 UTC, wieltar approved these changes

2020-11-18 11:17 UTC, TheLarsJansen approved these changes

2020-11-18 11:20 UTC, WilliamRossAvans approved these changes

2020-11-18 11:24 UTC, merged