[WIP] Transition scene
Rinkeeee96/FoxTrot_SA_Engine pull request #82
Opened 2020-11-15 17:00 UTC by Rinkeeee96

2020-11-16 17:32 UTC, WilliamRossAvans requested changes

2020-11-16 17:32 UTC, WilliamRossAvans commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +	// Todo
Er staat nog todo

2020-11-16 17:32 UTC, WilliamRossAvans commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +		if (progressBarFiller->getWidth() + generated > 685)
685 magic number

2020-11-16 17:32 UTC, WilliamRossAvans commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +		animation->setPositionX(animation->getPositionX() + 20);
+20 magic number

2020-11-16 17:32 UTC, WilliamRossAvans commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +			SceneSwitcher::get_instance().SwitchToScene("GAME");
Wil je niet dat je van buiten af kan aangeven naar welke scene je gaat.
Dit zodat het dynamischer gebruikt kan worden.

2020-11-16 17:34 UTC, TheLarsJansen requested changes

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Level.cpp
> +
Leeg?
Als iets leeg is hoeft het toch ook niet te bestaan?

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/MainMenu/MainMenu.cpp
> +#include "../../Buttons/PrimaryButton.h"
Relatieve paden willen we niet meer hebben
Heeft voor problemen gezorgd dus hebben gezegd dat we niet meer doen

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/MainMenu/MainMenu.cpp
>  	cout << "Start BTN" << endl;
debug couts horen niet op develop. Of met een debug macro
Is van andere PR I know maar zie het nu hier staan 😉

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/MainMenu/MainMenu.h
>  #include "SceneManager/Objects/Button.h"
Als je iets uit de game wil hebben moet dat via de API.h gaan. Is volgens mij van de Menu PR maar heb die volgens mij niet gereviewd dus vandaar dat het me hier opvalt

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Scenes.h
> +#include "./MainMenu/MainMenu.h"
Relatieve paden en GIT geeft een melding dat er geen new line at end of file is.
![image](https://user-images.githubusercontent.com/43005884/99286818-b7649000-2839-11eb-9c47-a6e744e58032.png)

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +}
Weer de melding van git dat er geen new line is
![image](https://user-images.githubusercontent.com/43005884/99287142-28a44300-283a-11eb-8c7f-33d3a1f97799.png)

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.h
> +#include "../../../../SceneSwitcher/SceneSwitcher.h"
Rel pad

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.h
> +#include "api.h"
API.h staat in de PCH.h ff kijken of het dus hier eruit kan en anders miss uit pch halen en dan overal bij zetten want nu ist dubbel

2020-11-16 17:34 UTC, TheLarsJansen commented on Glitch/Game/Scenes/Transitions/Transitions.h
> +#include "./GeneralTransition/GeneralTransition.h"
rel pad

2020-11-16 17:46 UTC, Rinkeeee96 commented on Glitch/Game/Level.cpp
> +
Functie moet wel bestaan ivm interface

2020-11-16 17:56 UTC, ttleeuw reviewed
Ziet er goed uit, zal hem goedkeuren als de feedback van @TheLarsJansen en @WilliamRossAvans is verwerkt

2020-11-16 17:56 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +		if (progressBarFiller->getWidth() + generated > 685)
Moet dit wel allemaal gedefined worden? In main menu staan ook alle getallen los voor bewegingen etc?

2020-11-16 17:56 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +			SceneSwitcher::get_instance().SwitchToScene("GAME");
Ja, maar we hebben hier nog geen manier voor. Dus moet ergens anders opgepakt worden.

2020-11-16 17:57 UTC, ttleeuw requested changes

2020-11-16 17:57 UTC, ttleeuw commented on Glitch/Game/Scenes/MainMenu/MainMenu.h
> +#include "../../../SceneSwitcher/SceneSwitcher.h"
Relatieve paden

2020-11-16 17:57 UTC, ttleeuw commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +#include "../../../SpriteState.h"
Relatieve paden

2020-11-16 17:57 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/MainMenu/MainMenu.cpp
>  	cout << "Start BTN" << endl;
Voor nu even laten staan omdat dit toch nog aangevuld moet worden.

2020-11-16 17:59 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Scenes.h
> +#include "./MainMenu/MainMenu.h"
Kijk even goed waar dit bestand voor dient. Dit is een koppel bestand zodat je op een andere plek alleen dit bestand hoeft te includen zodat je alles hebt kwa scenes. Daarom ook absolute paden.

2020-11-16 17:59 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Transitions/GeneralTransition/GeneralTransition.cpp
> +}
Git kan de pot op

2020-11-16 18:00 UTC, Rinkeeee96 commented on Glitch/Game/Scenes/Transitions/Transitions.h
> +#include "./GeneralTransition/GeneralTransition.h"
Kijk even goed waar dit bestand voor dient. Dit is een koppel bestand zodat je op een andere plek alleen dit bestand hoeft te includen zodat je alles hebt kwa scenes. Daarom ook absolute paden.

2020-11-16 19:55 UTC, TheLarsJansen approved these changes

2020-11-16 21:32 UTC, WilliamRossAvans approved these changes

2020-11-17 06:27 UTC, ttleeuw approved these changes

2020-11-17 06:27 UTC, merged