[WIP] Game win over
Rinkeeee96/FoxTrot_SA_Engine pull request #84
Opened 2020-11-15 20:00 UTC by WilliamRossAvans

2020-11-16 17:58 UTC, ttleeuw commented
PR hernoemen? Dit zijn de schermen neem ik aan?

2020-11-17 09:50 UTC, ttleeuw commented
Als level fix in develop zit, even pullen.  Benamingen zijn veranderd naar camelCasing

2020-11-19 16:42 UTC, TheLarsJansen requested changes
Weet niet hoe het kan dat hier allemaal nlohmann bestanden in "aangepast" zijn terwijl ze hetzelfde zijn. Verder even de "mis klik" bug fixen dan vind ik hem goed

2020-11-19 19:40 UTC, Rinkeeee96 approved these changes

2020-11-19 20:00 UTC, closed without merging