[WIP] Overworld
Rinkeeee96/FoxTrot_SA_Engine pull request #87
Opened 2020-11-16 19:21 UTC by Rinkeeee96

2020-11-17 09:49 UTC, ttleeuw commented
Als level fix in develop zit, even pullen.  Benamingen zijn veranderd naar camelCasing

2020-11-18 07:19 UTC, ttleeuw requested changes
Ik denk dat het laten zien dat een button "disabled" is wel in deze PR verwerkt kan worden, in verband met de overworld. Level2 button zou enabled moeten worden wanneer level1 pas is uitgespeeld.

2020-11-18 07:19 UTC, ttleeuw commented on Glitch/Game/Overworld/Overworld.cpp
> +#include "../Buttons/SecondaryButton.h"
Relatieve paden

2020-11-18 07:19 UTC, ttleeuw commented on Glitch/Game/Overworld/Overworld.h
> +#include "../../SceneSwitcher/SceneSwitcher.h"
Relatief pad

2020-11-18 07:19 UTC, ttleeuw commented on Glitch/Game/Overworld/Overworld.h
> +#include "SceneManager/Objects/Button.h"
Uit de engine, in de api.h zetten

2020-11-18 07:19 UTC, ttleeuw commented on Glitch/Game/Overworld/Overworld.h
> +#include "api.h"
word geinclude in de precompiled header

2020-11-18 07:19 UTC, ttleeuw commented on Glitch/pch.h
> +#include "./Game/Overworld/Overworld.h"
Behoort denk ik niet in de pch.h

2020-11-18 07:19 UTC, ttleeuw commented on engineFoxtrot/Engine/SceneManager/Scene.cpp
> +
Misschien mijn fout bij de fix, maar het zou kunnen dat delete layer gewoon aangeroepen kan worden

2020-11-18 07:19 UTC, ttleeuw commented
En doxygen?

2020-11-18 09:27 UTC, WilliamRossAvans requested changes
Ik zou vanuit overworld ook een transition scene laten zien

2020-11-18 09:27 UTC, WilliamRossAvans commented on Glitch/Game/Overworld/Overworld.cpp
> +#define CENTER_X  (WINDOW_WIDTH / 2)
Deze worden niet gebruikt

2020-11-18 09:27 UTC, WilliamRossAvans commented on Glitch/Game/Overworld/Overworld.cpp
> +	cout << "Level1 BTN" << endl;
cout kan weg

2020-11-18 09:51 UTC, wieltar submitted a review, later dismissed

2020-11-18 10:12 UTC, ttleeuw approved these changes

2020-11-18 10:26 UTC, wieltar approved these changes

2020-11-18 10:26 UTC, WilliamRossAvans approved these changes

2020-11-18 10:28 UTC, ttleeuw approved these changes

2020-11-18 10:28 UTC, merged