Level 1 32x32
Rinkeeee96/FoxTrot_SA_Engine pull request #94
Opened 2020-11-18 14:20 UTC by Maxvani

Het level is veranderd + naar 32x32 tiles gezet voor meer fps

2020-11-18 15:27 UTC, TheLarsJansen commented
Het level is nu groter dus dan moet het popetje ook groter

2020-11-19 15:44 UTC, WilliamRossAvans requested changes
De decoration is niet vergroot, ik zou deze ook vergroten

2020-11-19 16:06 UTC, TheLarsJansen approved these changes

2020-11-19 20:51 UTC, wieltar submitted a review, later dismissed

2020-11-20 08:09 UTC, ttleeuw requested changes
![image](https://user-images.githubusercontent.com/31704739/99775673-f5023b00-2b0f-11eb-8fc8-078641eaf5f5.png)

Menu en overworld lijken niet te kloppen

2020-11-20 09:33 UTC, Rinkeeee96 submitted a review, later dismissed

2020-11-20 10:30 UTC, wieltar approved these changes

2020-11-20 14:07 UTC, WilliamRossAvans submitted a review, later dismissed

2020-11-20 14:08 UTC, ttleeuw commented
Triggers in json

2020-11-20 15:53 UTC, wieltar approved these changes

2020-11-20 16:11 UTC, Rinkeeee96 approved these changes

2020-11-20 16:16 UTC, ttleeuw approved these changes

2020-11-20 16:22 UTC, TheLarsJansen approved these changes

2020-11-20 16:23 UTC, merged