Feature/ai
Rinkeeee96/FoxTrot_SA_Engine pull request #96
Opened 2020-11-19 09:47 UTC by ttleeuw

Branche is dirived from feature/game over game win triggers. Keep open until that branche is merged

2020-11-19 13:14 UTC, TheLarsJansen commented
Deze pas na gameOver gameWin branch mergen aangezien hij niet van develop maar van gameOvergameWin afkomt

2020-11-19 15:37 UTC, WilliamRossAvans requested changes

2020-11-19 15:37 UTC, WilliamRossAvans commented on Glitch/Game/Characters/Enemies/IEnemy.h
> +		if (Player* _player = dynamic_cast<Player*>(object)) {
Is deze check nodig? Je kan toch ook in de functie een Player* afdwingen?

2020-11-19 15:37 UTC, WilliamRossAvans commented on Glitch/Game/Levels/Level.cpp
> +void Level::setPlayer(Object* object) {
We kunnen toch ook gewoon een Player* afdwingen

2020-11-20 08:20 UTC, WilliamRossAvans commented on Glitch/Game/Characters/Enemies/IEnemy.h
> +		if (Player* _player = dynamic_cast<Player*>(object)) {
Was al opgelost

2020-11-20 08:25 UTC, WilliamRossAvans commented on Glitch/Game/Levels/Level.cpp
> +void Level::setPlayer(Object* object) {
is al in een andere brance opgelost

2020-11-20 08:28 UTC, WilliamRossAvans submitted a review, later dismissed

2020-11-20 09:23 UTC, TheLarsJansen commented on Glitch/Game/Levels/Builders/LevelBuilderDirector.cpp
> +				// TODO fix static draw objects
Static objects maar 1x drawen zouden we toch niet meer doen? Op advied van bob

2020-11-20 16:15 UTC, Maxvani approved these changes

2020-11-20 16:16 UTC, Rinkeeee96 approved these changes

2020-11-20 16:17 UTC, TheLarsJansen approved these changes

2020-11-20 16:17 UTC, merged